// ======================================================
// VERBAMUNDO — Spanish Vocabulary Data
// ======================================================

const DATA = {

  // Core verb list (infinitives with English, category, example)
  verbs: [
    // Movement
    {es:"caminar",en:"to walk",cat:"movement",ex:"Camino al mercado cada mañana."},
    {es:"correr",en:"to run",cat:"movement",ex:"Corre más rápido que yo."},
    {es:"saltar",en:"to jump",cat:"movement",ex:"El niño salta de alegría."},
    {es:"nadar",en:"to swim",cat:"movement",ex:"Nadamos en el río."},
    {es:"volar",en:"to fly",cat:"movement",ex:"Los pájaros vuelan al sur."},
    {es:"subir",en:"to climb/go up",cat:"movement",ex:"Subimos la montaña."},
    {es:"bajar",en:"to descend/go down",cat:"movement",ex:"Baja las escaleras con cuidado."},
    {es:"llegar",en:"to arrive",cat:"movement",ex:"Llegamos al amanecer."},
    {es:"partir",en:"to depart",cat:"movement",ex:"El tren parte a las ocho."},
    {es:"volver",en:"to return",cat:"movement",ex:"Vuelvo en una hora."},
    {es:"avanzar",en:"to advance",cat:"movement",ex:"El ejército avanzó hacia el norte."},
    {es:"retroceder",en:"to retreat",cat:"movement",ex:"Tuvimos que retroceder."},
    {es:"atravesar",en:"to cross/traverse",cat:"movement",ex:"Atravesamos el desierto."},
    {es:"escalar",en:"to scale/climb",cat:"movement",ex:"Escalan los Andes cada año."},
    {es:"arrastrarse",en:"to crawl/drag oneself",cat:"movement",ex:"Se arrastró por el barro."},

    // Communication
    {es:"hablar",en:"to speak",cat:"communication",ex:"Hablo español todos los días."},
    {es:"decir",en:"to say/tell",cat:"communication",ex:"¿Qué dijiste?"},
    {es:"contar",en:"to tell/count",cat:"communication",ex:"Cuenta la historia del pueblo."},
    {es:"narrar",en:"to narrate",cat:"communication",ex:"Narra los eventos históricos."},
    {es:"describir",en:"to describe",cat:"communication",ex:"Describe lo que ves."},
    {es:"explicar",en:"to explain",cat:"communication",ex:"El profesor explica la lección."},
    {es:"preguntar",en:"to ask",cat:"communication",ex:"Me pregunta mi nombre."},
    {es:"responder",en:"to respond",cat:"communication",ex:"Responde con calma."},
    {es:"gritar",en:"to shout",cat:"communication",ex:"Gritó de sorpresa."},
    {es:"susurrar",en:"to whisper",cat:"communication",ex:"Susurra en la oscuridad."},
    {es:"mencionar",en:"to mention",cat:"communication",ex:"Mencionó su viaje."},
    {es:"anunciar",en:"to announce",cat:"communication",ex:"Anunciaron la victoria."},
    {es:"proclamar",en:"to proclaim",cat:"communication",ex:"Proclamó la independencia."},
    {es:"declarar",en:"to declare",cat:"communication",ex:"El rey declaró la guerra."},
    {es:"confesar",en:"to confess",cat:"communication",ex:"Confesó su secreto."},

    // Thinking
    {es:"pensar",en:"to think",cat:"thinking",ex:"Pienso en ti."},
    {es:"creer",en:"to believe",cat:"thinking",ex:"Creo en la justicia."},
    {es:"saber",en:"to know (facts)",cat:"thinking",ex:"Sé la respuesta."},
    {es:"conocer",en:"to know (people/places)",cat:"thinking",ex:"Conozco esa ciudad."},
    {es:"recordar",en:"to remember",cat:"thinking",ex:"Recuerdo mis sueños."},
    {es:"olvidar",en:"to forget",cat:"thinking",ex:"Olvida el pasado."},
    {es:"imaginar",en:"to imagine",cat:"thinking",ex:"Imagina un mundo mejor."},
    {es:"soñar",en:"to dream",cat:"thinking",ex:"Sueña con las estrellas."},
    {es:"razonar",en:"to reason",cat:"thinking",ex:"Razona antes de actuar."},
    {es:"reflexionar",en:"to reflect",cat:"thinking",ex:"Reflexionó sobre su decisión."},
    {es:"analizar",en:"to analyze",cat:"thinking",ex:"Analiza los datos cuidadosamente."},
    {es:"comprender",en:"to understand",cat:"thinking",ex:"Comprendo tu situación."},
    {es:"intuir",en:"to sense/intuit",cat:"thinking",ex:"Intuí que algo pasaba."},
    {es:"adivinar",en:"to guess",cat:"thinking",ex:"Adivina qué es."},
    {es:"calcular",en:"to calculate",cat:"thinking",ex:"Calcula el total."},

    // Emotions
    {es:"amar",en:"to love",cat:"emotion",ex:"Te amo con todo mi corazón."},
    {es:"odiar",en:"to hate",cat:"emotion",ex:"Odia la injusticia."},
    {es:"temer",en:"to fear",cat:"emotion",ex:"Teme a la oscuridad."},
    {es:"alegrarse",en:"to be glad",cat:"emotion",ex:"Me alegro de verte."},
    {es:"entristecerse",en:"to become sad",cat:"emotion",ex:"Se entristece con las noticias."},
    {es:"enojarse",en:"to get angry",cat:"emotion",ex:"Se enoja fácilmente."},
    {es:"sorprender",en:"to surprise",cat:"emotion",ex:"La noticia me sorprendió."},
    {es:"asombrarse",en:"to be amazed",cat:"emotion",ex:"Me asombró el paisaje."},
    {es:"desesperar",en:"to despair",cat:"emotion",ex:"No desesperes."},
    {es:"esperanzar",en:"to give hope",cat:"emotion",ex:"Sus palabras me esperanzaron."},
    {es:"avergonzarse",en:"to be ashamed",cat:"emotion",ex:"Se avergüenza de mentir."},
    {es:"enorgullecerse",en:"to be proud",cat:"emotion",ex:"Me enorgullezco de ti."},
    {es:"angustiar",en:"to distress",cat:"emotion",ex:"La guerra angustia a todos."},
    {es:"consolar",en:"to console",cat:"emotion",ex:"La consoló con palabras suaves."},
    {es:"entristecer",en:"to sadden",cat:"emotion",ex:"Me entristece tu partida."},

    // Action
    {es:"hacer",en:"to do/make",cat:"action",ex:"Hace su tarea cada noche."},
    {es:"tomar",en:"to take/drink",cat:"action",ex:"Toma el autobús al trabajo."},
    {es:"dar",en:"to give",cat:"action",ex:"Da limosna a los pobres."},
    {es:"poner",en:"to put/place",cat:"action",ex:"Pon el libro en la mesa."},
    {es:"traer",en:"to bring",cat:"action",ex:"Trae agua del pozo."},
    {es:"llevar",en:"to carry/take",cat:"action",ex:"Lleva el mensaje al general."},
    {es:"abrir",en:"to open",cat:"action",ex:"Abre la puerta."},
    {es:"cerrar",en:"to close",cat:"action",ex:"Cierra los ojos."},
    {es:"romper",en:"to break",cat:"action",ex:"Rompió las cadenas."},
    {es:"construir",en:"to build",cat:"action",ex:"Construyen un puente."},
    {es:"destruir",en:"to destroy",cat:"action",ex:"El fuego destruyó el pueblo."},
    {es:"lanzar",en:"to throw/launch",cat:"action",ex:"Lanzó la piedra al río."},
    {es:"agarrar",en:"to grab/grasp",cat:"action",ex:"Agarra la cuerda."},
    {es:"soltar",en:"to release",cat:"action",ex:"Suelta el prisionero."},
    {es:"sostener",en:"to hold/sustain",cat:"action",ex:"Sostiene la antorcha en alto."},

    // Nature/environment
    {es:"florecer",en:"to bloom/flourish",cat:"nature",ex:"Las flores florecen en primavera."},
    {es:"crecer",en:"to grow",cat:"nature",ex:"Los árboles crecen lentamente."},
    {es:"sembrar",en:"to sow/plant",cat:"nature",ex:"Siembra maíz en el valle."},
    {es:"cosechar",en:"to harvest",cat:"nature",ex:"Cosechan el trigo en julio."},
    {es:"regar",en:"to water/irrigate",cat:"nature",ex:"Riega las plantas cada día."},
    {es:"brotar",en:"to sprout",cat:"nature",ex:"Brotan nuevas raíces."},
    {es:"marchitarse",en:"to wilt/wither",cat:"nature",ex:"Las rosas se marchitan sin agua."},
    {es:"arder",en:"to burn",cat:"nature",ex:"El bosque arde en verano."},
    {es:"inundar",en:"to flood",cat:"nature",ex:"El río inundó el pueblo."},
    {es:"desbordarse",en:"to overflow",cat:"nature",ex:"El lago se desbordó."},

    // Social
    {es:"gobernar",en:"to govern",cat:"social",ex:"Gobernó con justicia."},
    {es:"liderar",en:"to lead",cat:"social",ex:"Lidera el movimiento."},
    {es:"luchar",en:"to fight/struggle",cat:"social",ex:"Luchó por la libertad."},
    {es:"rebelarse",en:"to rebel",cat:"social",ex:"El pueblo se rebeló."},
    {es:"conquistar",en:"to conquer",cat:"social",ex:"Conquistaron nuevas tierras."},
    {es:"negociar",en:"to negotiate",cat:"social",ex:"Negociaron la paz."},
    {es:"acordar",en:"to agree/arrange",cat:"social",ex:"Acordaron un tratado."},
    {es:"unir",en:"to unite",cat:"social",ex:"Unió a las naciones."},
    {es:"separar",en:"to separate",cat:"social",ex:"Separaron los prisioneros."},
    {es:"liberar",en:"to liberate",cat:"social",ex:"Liberaron la ciudad."},
    {es:"oprimir",en:"to oppress",cat:"social",ex:"El régimen oprimía al pueblo."},
    {es:"resistir",en:"to resist",cat:"social",ex:"Resistieron durante años."},
    {es:"colaborar",en:"to collaborate",cat:"social",ex:"Colaboraron con los aliados."},
    {es:"rechazar",en:"to reject",cat:"social",ex:"Rechazaron las condiciones."},
    {es:"apoyar",en:"to support",cat:"social",ex:"Apoyó la revolución."},

    // More advanced
    {es:"abdicar",en:"to abdicate",cat:"advanced",ex:"El rey abdicó el trono."},
    {es:"ceder",en:"to cede/yield",cat:"advanced",ex:"Cedió el territorio."},
    {es:"reivindicar",en:"to reclaim/demand",cat:"advanced",ex:"Reivindican sus derechos."},
    {es:"promulgar",en:"to promulgate",cat:"advanced",ex:"Promulgaron la constitución."},
    {es:"derogar",en:"to repeal",cat:"advanced",ex:"Derogaron la ley antigua."},
    {es:"abolir",en:"to abolish",cat:"advanced",ex:"Abolieron la esclavitud."},
    {es:"instaurar",en:"to establish/institute",cat:"advanced",ex:"Instauraron la república."},
    {es:"derrocar",en:"to overthrow",cat:"advanced",ex:"Derrocaron al dictador."},
    {es:"exiliar",en:"to exile",cat:"advanced",ex:"Exiliaron al poeta."},
    {es:"ejecutar",en:"to execute/carry out",cat:"advanced",ex:"Ejecutaron el plan."},
    {es:"emancipar",en:"to emancipate",cat:"advanced",ex:"Emanciparon a los esclavos."},
    {es:"subyugar",en:"to subjugate",cat:"advanced",ex:"Subyugaron a los pueblos nativos."},
    {es:"insurgir",en:"to rise up",cat:"advanced",ex:"El pueblo insurgió contra la corona."},
    {es:"capitular",en:"to capitulate",cat:"advanced",ex:"El ejército capituló al amanecer."},
    {es:"reconciliarse",en:"to reconcile",cat:"advanced",ex:"Las naciones se reconciliaron."},
    {es:"fusilar",en:"to execute by firing squad",cat:"advanced",ex:"Fusilaron a los líderes."},
    {es:"indultar",en:"to pardon",cat:"advanced",ex:"El presidente indultó al preso."},
    {es:"saquear",en:"to loot/plunder",cat:"advanced",ex:"Saquearon la ciudad conquistada."},
    {es:"devastar",en:"to devastate",cat:"advanced",ex:"La guerra devastó la región."},
    {es:"reconstruir",en:"to reconstruct",cat:"advanced",ex:"Reconstruyeron el país tras la guerra."},
  ],

  // Food categories for naming game
  food: {
    frutas: ["manzana","pera","plátano","naranja","mango","papaya","guayaba","maracuyá","chirimoya","tamarindo","nance","mamey","zapote","pitaya","carambola","coco","piña","melón","sandía","uva","cereza","higo","granada","durazno","ciruela","frambuesa","fresa","mora","arándano","lichi"],
    verduras: ["zanahoria","lechuga","espinaca","brócoli","coliflor","pepino","jitomate","aguacate","cebolla","ajo","pimiento","chile","calabaza","chayote","nopal","jícama","betabel","apio","cilantro","perejil","epazote","hierba santa","quelite","verdolaga","rábano","ejote","chícharo","haba","lenteja","garbanzo"],
    carnes: ["pollo","res","cerdo","borrego","chivo","conejo","pato","pavo","venado","jabalí","armadillo","iguana","camarón","langosta","pulpo","calamar","mejillón","almeja","cangrejo","caracol"],
    granos: ["maíz","frijol","arroz","trigo","quinoa","amaranto","chía","cacahuate","nuez","almendra","pepita","ajonjolí","linaza","avena","cebada","sorgo"],
    platillos: ["tamale","enchilada","taco","pozole","mole","chile relleno","ceviche","sopa de lima","cochinita pibil","chiles en nogada","huarache","tlayuda","memela","tlacuyo","quesadilla","gordita","sope","tostada","chalupa","flautas","chilaquiles","enfrijoladas","entomatadas","menudo","birria","barbacoa","carnitas","chuleta","milanesa","caldo de pollo"],
    bebidas: ["agua fresca","horchata","tamarindo","jamaica","tejuino","tepache","pulque","mezcal","tequila","atole","champurrado","café de olla","chocolate caliente","jugo de caña","caldo de camarón","agua de coco","licuado","batido","ponche","rompope"],
  },

  // Animals in Spanish
  animals: ["perro","gato","caballo","vaca","cerdo","oveja","cabra","burro","llama","alpaca","vicuña","guanaco","jaguar","puma","ocelote","tapir","pecarí","capibara","nutria","coatí","mapache","armadillo","tlacuache","zorrillo","coyote","lobo","zorro","oso","venado","conejo","ardilla","tuza","ratón","murciélago","serpiente","iguana","cocodrilo","caimán","tortuga","sapo","rana","ajolote","mariposa","abeja","hormiga","mosquito","libélula","chapulín","escarabajo","araña","escorpión","águila","halcón","quetzal","tucán","loro","guacamaya","colibrí","pelícano","flamenco","garza","cóndor","buitre"],

  // History stories for reading comprehension
  stories: [
    {
      title: "La Independencia de México",
      level: "intermediate",
      text: `El 16 de septiembre de 1810, el cura Miguel Hidalgo pronunció el famoso Grito de Independencia en el pueblo de Dolores, Guanajuato. Este acto {1} el inicio de la guerra de independencia que {2} durante once años. El movimiento insurgente {3} a miles de campesinos e indígenas que {4} contra el dominio colonial español. Finalmente, el 27 de septiembre de 1821, el Ejército Trigarante, liderado por Agustín de Iturbide, {5} triunfante a la Ciudad de México, {6} así la independencia nacional. Este proceso histórico {7} profundamente la identidad del pueblo mexicano y {8} las bases de una nueva nación soberana.`,
      blanks: [
        {pos:1, options:["marcó","señaló","inició","comenzó"], correct:0, hint:"to mark/indicate"},
        {pos:2, options:["duraba","duró","duraría","durara"], correct:1, hint:"preterite of durar"},
        {pos:3, options:["atrajo","atraía","atrae","atraiga"], correct:0, hint:"attracted (preterite)"},
        {pos:4, options:["luchaban","lucharon","lucharán","luchen"], correct:0, hint:"were fighting (imperfect)"},
        {pos:5, options:["entró","entra","entrara","entrará"], correct:0, hint:"entered (preterite)"},
        {pos:6, options:["consolidando","consolidar","consolidó","consolidase"], correct:0, hint:"consolidating (gerund)"},
        {pos:7, options:["transformó","transforma","transforme","transformara"], correct:0, hint:"transformed (preterite)"},
        {pos:8, options:["estableció","establece","estableciera","establecerá"], correct:0, hint:"established (preterite)"},
      ],
      vocab: [
        {word:"cura",def:"priest"},
        {word:"pronunció",def:"pronounced/delivered"},
        {word:"insurgente",def:"insurgent/rebel"},
        {word:"campesino",def:"peasant/farmer"},
        {word:"dominio",def:"domination/rule"},
        {word:"soberana",def:"sovereign"},
      ]
    },
    {
      title: "Los Aztecas y Tenochtitlán",
      level: "intermediate",
      text: `Los aztecas, también conocidos como mexicas, {1} en el Valle de México alrededor del siglo XIV. Según la leyenda, sus dioses les {2} que {3} su ciudad donde {4} un águila {5} una serpiente sobre un nopal. En 1325, {6} Tenochtitlán sobre un islote en el lago Texcoco. La ciudad {7} rápidamente y {8} convertirse en una de las más grandes del mundo, con una población estimada de 200,000 habitantes. Los aztecas {9} un poderoso imperio que {10} a los pueblos vecinos mediante la guerra y la diplomacia.`,
      blanks: [
        {pos:1, options:["se establecieron","establecían","establezcan","se establecen"], correct:0, hint:"settled (reflexive preterite)"},
        {pos:2, options:["ordenaron","ordenaban","ordenarán","ordenen"], correct:0, hint:"ordered (preterite)"},
        {pos:3, options:["fundaran","fundarán","fundaron","fundan"], correct:0, hint:"they should found (subj.)"},
        {pos:4, options:["vieran","vieron","verían","ven"], correct:0, hint:"they would see (subj.)"},
        {pos:5, options:["devorando","devoró","devore","devorar"], correct:0, hint:"devouring (gerund)"},
        {pos:6, options:["fundaron","fundan","fundaban","fundarán"], correct:0, hint:"founded (preterite)"},
        {pos:7, options:["creció","crece","crecía","crezca"], correct:0, hint:"grew (preterite)"},
        {pos:8, options:["llegó a","llega a","llegará a","llegara a"], correct:0, hint:"came to (preterite + a)"},
        {pos:9, options:["construyeron","construyen","construían","construirán"], correct:0, hint:"built/constructed (preterite)"},
        {pos:10, options:["controló","controla","controlaba","controlará"], correct:0, hint:"controlled (preterite)"},
      ],
      vocab: [
        {word:"islote",def:"small island"},
        {word:"nopal",def:"cactus"},
        {word:"devorando",def:"devouring"},
        {word:"estimada",def:"estimated"},
        {word:"diplomacia",def:"diplomacy"},
        {word:"poderoso",def:"powerful"},
      ]
    },
    {
      title: "Simón Bolívar: El Libertador",
      level: "advanced",
      text: `Simón Bolívar, nacido en Caracas en 1783, {1} el sueño de unificar América del Sur en una gran nación libre del dominio español. Después de múltiples fracasos y exilios, {2} victorias cruciales en batallas como Boyacá (1819) y Carabobo (1821). Su visión {3} la creación de la Gran Colombia, una república que {4} Venezuela, Colombia, Ecuador y Panamá. Sin embargo, las tensiones políticas y los intereses regionales {5} su proyecto. Las naciones {6} separarse y Bolívar, {7} y enfermo, {8} en 1830 sin ver realizado su sueño continental. Su legado, sin embargo, {9} vivo en la memoria colectiva latinoamericana y lo {10} como el Padre de la Patria en varios países.`,
      blanks: [
        {pos:1, options:["persiguió","persigue","perseguía","perseguirá"], correct:2, hint:"was pursuing (imperfect - ongoing dream)"},
        {pos:2, options:["alcanzó","alcanza","alcanzara","alcanzaría"], correct:0, hint:"achieved (preterite)"},
        {pos:3, options:["contemplaba","contempló","contemple","contemplará"], correct:0, hint:"contemplated/envisioned (imperfect)"},
        {pos:4, options:["integrara","integró","integra","integrará"], correct:0, hint:"would integrate (subj.)"},
        {pos:5, options:["frustraron","frustran","frustrarán","frustren"], correct:0, hint:"frustrated (preterite)"},
        {pos:6, options:["prefirieron","prefieren","preferirían","prefieran"], correct:0, hint:"preferred (preterite)"},
        {pos:7, options:["desilusionado","desilusionar","desilusiona","desilusionando"], correct:0, hint:"disillusioned (past participle adj.)"},
        {pos:8, options:["falleció","fallece","fallecería","falleciera"], correct:0, hint:"passed away (preterite)"},
        {pos:9, options:["pervive","pervivió","pervivía","perviva"], correct:0, hint:"lives on (present - still true)"},
        {pos:10, options:["honran","honraron","honrarán","honren"], correct:0, hint:"honor (present - still true)"},
      ],
      vocab: [
        {word:"fracasos",def:"failures"},
        {word:"exilios",def:"exiles"},
        {word:"desilusionado",def:"disillusioned"},
        {word:"legado",def:"legacy"},
        {word:"colectiva",def:"collective"},
        {word:"contemplaba",def:"envisioned/contemplated"},
      ]
    },
  ],

  // Conjugation challenge data
  conjugations: [
    {verb:"hablar", tense:"presente", forms:{yo:"hablo",tú:"hablas",él:"habla","nosotros":"hablamos","ellos":"hablan"}, type:"regular"},
    {verb:"comer", tense:"presente", forms:{yo:"como",tú:"comes",él:"come","nosotros":"comemos","ellos":"comen"}, type:"regular"},
    {verb:"vivir", tense:"presente", forms:{yo:"vivo",tú:"vives",él:"vive","nosotros":"vivimos","ellos":"viven"}, type:"regular"},
    {verb:"ser", tense:"presente", forms:{yo:"soy",tú:"eres",él:"es","nosotros":"somos","ellos":"son"}, type:"irregular"},
    {verb:"estar", tense:"presente", forms:{yo:"estoy",tú:"estás",él:"está","nosotros":"estamos","ellos":"están"}, type:"irregular"},
    {verb:"tener", tense:"presente", forms:{yo:"tengo",tú:"tienes",él:"tiene","nosotros":"tenemos","ellos":"tienen"}, type:"irregular"},
    {verb:"ir", tense:"presente", forms:{yo:"voy",tú:"vas",él:"va","nosotros":"vamos","ellos":"van"}, type:"irregular"},
    {verb:"poder", tense:"presente", forms:{yo:"puedo",tú:"puedes",él:"puede","nosotros":"podemos","ellos":"pueden"}, type:"stem-change"},
    {verb:"querer", tense:"presente", forms:{yo:"quiero",tú:"quieres",él:"quiere","nosotros":"queremos","ellos":"quieren"}, type:"stem-change"},
    {verb:"saber", tense:"presente", forms:{yo:"sé",tú:"sabes",él:"sabe","nosotros":"sabemos","ellos":"saben"}, type:"irregular"},
    {verb:"hablar", tense:"pretérito", forms:{yo:"hablé",tú:"hablaste",él:"habló","nosotros":"hablamos","ellos":"hablaron"}, type:"regular"},
    {verb:"comer", tense:"pretérito", forms:{yo:"comí",tú:"comiste",él:"comió","nosotros":"comimos","ellos":"comieron"}, type:"regular"},
    {verb:"ir", tense:"pretérito", forms:{yo:"fui",tú:"fuiste",él:"fue","nosotros":"fuimos","ellos":"fueron"}, type:"irregular"},
    {verb:"ser", tense:"pretérito", forms:{yo:"fui",tú:"fuiste",él:"fue","nosotros":"fuimos","ellos":"fueron"}, type:"irregular"},
    {verb:"tener", tense:"pretérito", forms:{yo:"tuve",tú:"tuviste",él:"tuvo","nosotros":"tuvimos","ellos":"tuvieron"}, type:"irregular"},
    {verb:"hacer", tense:"pretérito", forms:{yo:"hice",tú:"hiciste",él:"hizo","nosotros":"hicimos","ellos":"hicieron"}, type:"irregular"},
    {verb:"poder", tense:"pretérito", forms:{yo:"pude",tú:"pudiste",él:"pudo","nosotros":"pudimos","ellos":"pudieron"}, type:"irregular"},
    {verb:"hablar", tense:"imperfecto", forms:{yo:"hablaba",tú:"hablabas",él:"hablaba","nosotros":"hablábamos","ellos":"hablaban"}, type:"regular"},
    {verb:"tener", tense:"futuro", forms:{yo:"tendré",tú:"tendrás",él:"tendrá","nosotros":"tendremos","ellos":"tendrán"}, type:"irregular"},
    {verb:"hablar", tense:"futuro", forms:{yo:"hablaré",tú:"hablarás",él:"hablará","nosotros":"hablaremos","ellos":"hablarán"}, type:"regular"},
  ],

  // Word pairs for translation game (EN -> ES)
  wordPairs: [
    // Basic
    {en:"freedom",es:"libertad"},{en:"homeland",es:"patria"},{en:"people",es:"pueblo"},
    {en:"king",es:"rey"},{en:"queen",es:"reina"},{en:"war",es:"guerra"},
    {en:"peace",es:"paz"},{en:"land",es:"tierra"},{en:"river",es:"río"},
    {en:"mountain",es:"montaña"},{en:"city",es:"ciudad"},{en:"village",es:"aldea"},
    {en:"soldier",es:"soldado"},{en:"leader",es:"líder"},{en:"enemy",es:"enemigo"},
    // History
    {en:"independence",es:"independencia"},{en:"revolution",es:"revolución"},
    {en:"constitution",es:"constitución"},{en:"congress",es:"congreso"},
    {en:"treaty",es:"tratado"},{en:"colony",es:"colonia"},
    {en:"empire",es:"imperio"},{en:"republic",es:"república"},
    {en:"democracy",es:"democracia"},{en:"slavery",es:"esclavitud"},
    {en:"indigenous",es:"indígena"},{en:"colonizer",es:"colonizador"},
    {en:"rebellion",es:"rebelión"},{en:"resistance",es:"resistencia"},
    {en:"liberation",es:"liberación"},{en:"conquest",es:"conquista"},
    // Advanced
    {en:"sovereignty",es:"soberanía"},{en:"nationalism",es:"nacionalismo"},
    {en:"oppression",es:"opresión"},{en:"reform",es:"reforma"},
    {en:"alliance",es:"alianza"},{en:"betrayal",es:"traición"},
    {en:"exile",es:"exilio"},{en:"legacy",es:"legado"},
    {en:"uprising",es:"levantamiento"},{en:"ceasefire",es:"alto al fuego"},
    {en:"declaration",es:"declaración"},{en:"ambassador",es:"embajador"},
    {en:"territory",es:"territorio"},{en:"border",es:"frontera"},
    {en:"wealth",es:"riqueza"},{en:"poverty",es:"pobreza"},
    // Nature/food
    {en:"corn/maize",es:"maíz"},{en:"cacao",es:"cacao"},
    {en:"avocado",es:"aguacate"},{en:"chili pepper",es:"chile"},
    {en:"jungle",es:"selva"},{en:"volcano",es:"volcán"},
    {en:"earthquake",es:"terremoto"},{en:"harvest",es:"cosecha"},
    {en:"drought",es:"sequía"},{en:"flood",es:"inundación"},
  ],

  // Hangman word bank with hints
  hangmanWords: [
    {word:"independencia",hint:"freedom from colonial rule"},
    {word:"revolución",hint:"major political upheaval"},
    {word:"libertador",hint:"title given to Simón Bolívar"},
    {word:"conquistador",hint:"Spanish explorer-soldier"},
    {word:"constitución",hint:"fundamental law document"},
    {word:"civilización",hint:"advanced human society"},
    {word:"esclavitud",hint:"the state of being enslaved"},
    {word:"emancipación",hint:"freedom from bondage"},
    {word:"mestizo",hint:"mixed Indigenous-European heritage"},
    {word:"caudillo",hint:"Latin American military leader"},
    {word:"hacienda",hint:"large rural estate"},
    {word:"malinche",hint:"Aztec interpreter for Cortés"},
    {word:"tlacuache",hint:"a marsupial native to Mexico"},
    {word:"quetzal",hint:"sacred bird of Guatemala"},
    {word:"aguacate",hint:"buttery green fruit"},
    {word:"chocolate",hint:"came from cacao, Aztec gift to the world"},
    {word:"huracán",hint:"powerful tropical storm"},
    {word:"volcán",hint:"mountain that erupts"},
    {word:"mariposa",hint:"butterfly"},
    {word:"murciélago",hint:"the only flying mammal"},
    {word:"chapulín",hint:"edible insect, also a TV character"},
    {word:"ferrocarril",hint:"trains run on this"},
    {word:"guerrillero",hint:"irregular warfare fighter"},
    {word:"pronunciamiento",hint:"military declaration of revolt"},
    {word:"tenochtitlán",hint:"Aztec capital, now Mexico City"},
    {word:"copacabana",hint:"Bolivian city on Lake Titicaca"},
    {word:"patagonia",hint:"southern tip of South America"},
    {word:"amazonia",hint:"vast South American rainforest"},
  ],
};
