// ======================================================
// VERBAMUNDO — Spanish Vocabulary Data
// ======================================================

const DATA = {

  // Core verb list (infinitives with English, category, example)
  verbs: [
    // Movement
    {es:"caminar",en:"to walk",cat:"movement",ex:"Camino al mercado cada mañana."},
    {es:"correr",en:"to run",cat:"movement",ex:"Corre más rápido que yo."},
    {es:"saltar",en:"to jump",cat:"movement",ex:"El niño salta de alegría."},
    {es:"nadar",en:"to swim",cat:"movement",ex:"Nadamos en el río."},
    {es:"volar",en:"to fly",cat:"movement",ex:"Los pájaros vuelan al sur."},
    {es:"subir",en:"to climb/go up",cat:"movement",ex:"Subimos la montaña."},
    {es:"bajar",en:"to descend/go down",cat:"movement",ex:"Baja las escaleras con cuidado."},
    {es:"llegar",en:"to arrive",cat:"movement",ex:"Llegamos al amanecer."},
    {es:"partir",en:"to depart",cat:"movement",ex:"El tren parte a las ocho."},
    {es:"volver",en:"to return",cat:"movement",ex:"Vuelvo en una hora."},
    {es:"avanzar",en:"to advance",cat:"movement",ex:"El ejército avanzó hacia el norte."},
    {es:"retroceder",en:"to retreat",cat:"movement",ex:"Tuvimos que retroceder."},
    {es:"atravesar",en:"to cross/traverse",cat:"movement",ex:"Atravesamos el desierto."},
    {es:"escalar",en:"to scale/climb",cat:"movement",ex:"Escalan los Andes cada año."},
    {es:"arrastrarse",en:"to crawl/drag oneself",cat:"movement",ex:"Se arrastró por el barro."},

    // Communication
    {es:"hablar",en:"to speak",cat:"communication",ex:"Hablo español todos los días."},
    {es:"decir",en:"to say/tell",cat:"communication",ex:"¿Qué dijiste?"},
    {es:"contar",en:"to tell/count",cat:"communication",ex:"Cuenta la historia del pueblo."},
    {es:"narrar",en:"to narrate",cat:"communication",ex:"Narra los eventos históricos."},
    {es:"describir",en:"to describe",cat:"communication",ex:"Describe lo que ves."},
    {es:"explicar",en:"to explain",cat:"communication",ex:"El profesor explica la lección."},
    {es:"preguntar",en:"to ask",cat:"communication",ex:"Me pregunta mi nombre."},
    {es:"responder",en:"to respond",cat:"communication",ex:"Responde con calma."},
    {es:"gritar",en:"to shout",cat:"communication",ex:"Gritó de sorpresa."},
    {es:"susurrar",en:"to whisper",cat:"communication",ex:"Susurra en la oscuridad."},
    {es:"mencionar",en:"to mention",cat:"communication",ex:"Mencionó su viaje."},
    {es:"anunciar",en:"to announce",cat:"communication",ex:"Anunciaron la victoria."},
    {es:"proclamar",en:"to proclaim",cat:"communication",ex:"Proclamó la independencia."},
    {es:"declarar",en:"to declare",cat:"communication",ex:"El rey declaró la guerra."},
    {es:"confesar",en:"to confess",cat:"communication",ex:"Confesó su secreto."},

    // Thinking
    {es:"pensar",en:"to think",cat:"thinking",ex:"Pienso en ti."},
    {es:"creer",en:"to believe",cat:"thinking",ex:"Creo en la justicia."},
    {es:"saber",en:"to know (facts)",cat:"thinking",ex:"Sé la respuesta."},
    {es:"conocer",en:"to know (people/places)",cat:"thinking",ex:"Conozco esa ciudad."},
    {es:"recordar",en:"to remember",cat:"thinking",ex:"Recuerdo mis sueños."},
    {es:"olvidar",en:"to forget",cat:"thinking",ex:"Olvida el pasado."},
    {es:"imaginar",en:"to imagine",cat:"thinking",ex:"Imagina un mundo mejor."},
    {es:"soñar",en:"to dream",cat:"thinking",ex:"Sueña con las estrellas."},
    {es:"razonar",en:"to reason",cat:"thinking",ex:"Razona antes de actuar."},
    {es:"reflexionar",en:"to reflect",cat:"thinking",ex:"Reflexionó sobre su decisión."},
    {es:"analizar",en:"to analyze",cat:"thinking",ex:"Analiza los datos cuidadosamente."},
    {es:"comprender",en:"to understand",cat:"thinking",ex:"Comprendo tu situación."},
    {es:"intuir",en:"to sense/intuit",cat:"thinking",ex:"Intuí que algo pasaba."},
    {es:"adivinar",en:"to guess",cat:"thinking",ex:"Adivina qué es."},
    {es:"calcular",en:"to calculate",cat:"thinking",ex:"Calcula el total."},

    // Emotions
    {es:"amar",en:"to love",cat:"emotion",ex:"Te amo con todo mi corazón."},
    {es:"odiar",en:"to hate",cat:"emotion",ex:"Odia la injusticia."},
    {es:"temer",en:"to fear",cat:"emotion",ex:"Teme a la oscuridad."},
    {es:"alegrarse",en:"to be glad",cat:"emotion",ex:"Me alegro de verte."},
    {es:"entristecerse",en:"to become sad",cat:"emotion",ex:"Se entristece con las noticias."},
    {es:"enojarse",en:"to get angry",cat:"emotion",ex:"Se enoja fácilmente."},
    {es:"sorprender",en:"to surprise",cat:"emotion",ex:"La noticia me sorprendió."},
    {es:"asombrarse",en:"to be amazed",cat:"emotion",ex:"Me asombró el paisaje."},
    {es:"desesperar",en:"to despair",cat:"emotion",ex:"No desesperes."},
    {es:"esperanzar",en:"to give hope",cat:"emotion",ex:"Sus palabras me esperanzaron."},
    {es:"avergonzarse",en:"to be ashamed",cat:"emotion",ex:"Se avergüenza de mentir."},
    {es:"enorgullecerse",en:"to be proud",cat:"emotion",ex:"Me enorgullezco de ti."},
    {es:"angustiar",en:"to distress",cat:"emotion",ex:"La guerra angustia a todos."},
    {es:"consolar",en:"to console",cat:"emotion",ex:"La consoló con palabras suaves."},
    {es:"entristecer",en:"to sadden",cat:"emotion",ex:"Me entristece tu partida."},

    // Action
    {es:"hacer",en:"to do/make",cat:"action",ex:"Hace su tarea cada noche."},
    {es:"tomar",en:"to take/drink",cat:"action",ex:"Toma el autobús al trabajo."},
    {es:"dar",en:"to give",cat:"action",ex:"Da limosna a los pobres."},
    {es:"poner",en:"to put/place",cat:"action",ex:"Pon el libro en la mesa."},
    {es:"traer",en:"to bring",cat:"action",ex:"Trae agua del pozo."},
    {es:"llevar",en:"to carry/take",cat:"action",ex:"Lleva el mensaje al general."},
    {es:"abrir",en:"to open",cat:"action",ex:"Abre la puerta."},
    {es:"cerrar",en:"to close",cat:"action",ex:"Cierra los ojos."},
    {es:"romper",en:"to break",cat:"action",ex:"Rompió las cadenas."},
    {es:"construir",en:"to build",cat:"action",ex:"Construyen un puente."},
    {es:"destruir",en:"to destroy",cat:"action",ex:"El fuego destruyó el pueblo."},
    {es:"lanzar",en:"to throw/launch",cat:"action",ex:"Lanzó la piedra al río."},
    {es:"agarrar",en:"to grab/grasp",cat:"action",ex:"Agarra la cuerda."},
    {es:"soltar",en:"to release",cat:"action",ex:"Suelta el prisionero."},
    {es:"sostener",en:"to hold/sustain",cat:"action",ex:"Sostiene la antorcha en alto."},

    // Nature/environment
    {es:"florecer",en:"to bloom/flourish",cat:"nature",ex:"Las flores florecen en primavera."},
    {es:"crecer",en:"to grow",cat:"nature",ex:"Los árboles crecen lentamente."},
    {es:"sembrar",en:"to sow/plant",cat:"nature",ex:"Siembra maíz en el valle."},
    {es:"cosechar",en:"to harvest",cat:"nature",ex:"Cosechan el trigo en julio."},
    {es:"regar",en:"to water/irrigate",cat:"nature",ex:"Riega las plantas cada día."},
    {es:"brotar",en:"to sprout",cat:"nature",ex:"Brotan nuevas raíces."},
    {es:"marchitarse",en:"to wilt/wither",cat:"nature",ex:"Las rosas se marchitan sin agua."},
    {es:"arder",en:"to burn",cat:"nature",ex:"El bosque arde en verano."},
    {es:"inundar",en:"to flood",cat:"nature",ex:"El río inundó el pueblo."},
    {es:"desbordarse",en:"to overflow",cat:"nature",ex:"El lago se desbordó."},

    // Social
    {es:"gobernar",en:"to govern",cat:"social",ex:"Gobernó con justicia."},
    {es:"liderar",en:"to lead",cat:"social",ex:"Lidera el movimiento."},
    {es:"luchar",en:"to fight/struggle",cat:"social",ex:"Luchó por la libertad."},
    {es:"rebelarse",en:"to rebel",cat:"social",ex:"El pueblo se rebeló."},
    {es:"conquistar",en:"to conquer",cat:"social",ex:"Conquistaron nuevas tierras."},
    {es:"negociar",en:"to negotiate",cat:"social",ex:"Negociaron la paz."},
    {es:"acordar",en:"to agree/arrange",cat:"social",ex:"Acordaron un tratado."},
    {es:"unir",en:"to unite",cat:"social",ex:"Unió a las naciones."},
    {es:"separar",en:"to separate",cat:"social",ex:"Separaron los prisioneros."},
    {es:"liberar",en:"to liberate",cat:"social",ex:"Liberaron la ciudad."},
    {es:"oprimir",en:"to oppress",cat:"social",ex:"El régimen oprimía al pueblo."},
    {es:"resistir",en:"to resist",cat:"social",ex:"Resistieron durante años."},
    {es:"colaborar",en:"to collaborate",cat:"social",ex:"Colaboraron con los aliados."},
    {es:"rechazar",en:"to reject",cat:"social",ex:"Rechazaron las condiciones."},
    {es:"apoyar",en:"to support",cat:"social",ex:"Apoyó la revolución."},

    // More advanced
    {es:"abdicar",en:"to abdicate",cat:"advanced",ex:"El rey abdicó el trono."},
    {es:"ceder",en:"to cede/yield",cat:"advanced",ex:"Cedió el territorio."},
    {es:"reivindicar",en:"to reclaim/demand",cat:"advanced",ex:"Reivindican sus derechos."},
    {es:"promulgar",en:"to promulgate",cat:"advanced",ex:"Promulgaron la constitución."},
    {es:"derogar",en:"to repeal",cat:"advanced",ex:"Derogaron la ley antigua."},
    {es:"abolir",en:"to abolish",cat:"advanced",ex:"Abolieron la esclavitud."},
    {es:"instaurar",en:"to establish/institute",cat:"advanced",ex:"Instauraron la república."},
    {es:"derrocar",en:"to overthrow",cat:"advanced",ex:"Derrocaron al dictador."},
    {es:"exiliar",en:"to exile",cat:"advanced",ex:"Exiliaron al poeta."},
    {es:"ejecutar",en:"to execute/carry out",cat:"advanced",ex:"Ejecutaron el plan."},
    {es:"emancipar",en:"to emancipate",cat:"advanced",ex:"Emanciparon a los esclavos."},
    {es:"subyugar",en:"to subjugate",cat:"advanced",ex:"Subyugaron a los pueblos nativos."},
    {es:"insurgir",en:"to rise up",cat:"advanced",ex:"El pueblo insurgió contra la corona."},
    {es:"capitular",en:"to capitulate",cat:"advanced",ex:"El ejército capituló al amanecer."},
    {es:"reconciliarse",en:"to reconcile",cat:"advanced",ex:"Las naciones se reconciliaron."},
    {es:"fusilar",en:"to execute by firing squad",cat:"advanced",ex:"Fusilaron a los líderes."},
    {es:"indultar",en:"to pardon",cat:"advanced",ex:"El presidente indultó al preso."},
    {es:"saquear",en:"to loot/plunder",cat:"advanced",ex:"Saquearon la ciudad conquistada."},
    {es:"devastar",en:"to devastate",cat:"advanced",ex:"La guerra devastó la región."},
    {es:"reconstruir",en:"to reconstruct",cat:"advanced",ex:"Reconstruyeron el país tras la guerra."},
  ],

  // Food categories for naming game
  food: {
    frutas: ["manzana","pera","plátano","naranja","mango","papaya","guayaba","maracuyá","chirimoya","tamarindo","nance","mamey","zapote","pitaya","carambola","coco","piña","melón","sandía","uva","cereza","higo","granada","durazno","ciruela","frambuesa","fresa","mora","arándano","lichi"],
    verduras: ["zanahoria","lechuga","espinaca","brócoli","coliflor","pepino","jitomate","aguacate","cebolla","ajo","pimiento","chile","calabaza","chayote","nopal","jícama","betabel","apio","cilantro","perejil","epazote","hierba santa","quelite","verdolaga","rábano","ejote","chícharo","haba","lenteja","garbanzo"],
    carnes: ["pollo","res","cerdo","borrego","chivo","conejo","pato","pavo","venado","jabalí","armadillo","iguana","camarón","langosta","pulpo","calamar","mejillón","almeja","cangrejo","caracol"],
    granos: ["maíz","frijol","arroz","trigo","quinoa","amaranto","chía","cacahuate","nuez","almendra","pepita","ajonjolí","linaza","avena","cebada","sorgo"],
    platillos: ["tamale","enchilada","taco","pozole","mole","chile relleno","ceviche","sopa de lima","cochinita pibil","chiles en nogada","huarache","tlayuda","memela","tlacuyo","quesadilla","gordita","sope","tostada","chalupa","flautas","chilaquiles","enfrijoladas","entomatadas","menudo","birria","barbacoa","carnitas","chuleta","milanesa","caldo de pollo"],
    bebidas: ["agua fresca","horchata","tamarindo","jamaica","tejuino","tepache","pulque","mezcal","tequila","atole","champurrado","café de olla","chocolate caliente","jugo de caña","caldo de camarón","agua de coco","licuado","batido","ponche","rompope"],
  },

  // Animals in Spanish
  animals: ["perro","gato","caballo","vaca","cerdo","oveja","cabra","burro","llama","alpaca","vicuña","guanaco","jaguar","puma","ocelote","tapir","pecarí","capibara","nutria","coatí","mapache","armadillo","tlacuache","zorrillo","coyote","lobo","zorro","oso","venado","conejo","ardilla","tuza","ratón","murciélago","serpiente","iguana","cocodrilo","caimán","tortuga","sapo","rana","ajolote","mariposa","abeja","hormiga","mosquito","libélula","chapulín","escarabajo","araña","escorpión","águila","halcón","quetzal","tucán","loro","guacamaya","colibrí","pelícano","flamenco","garza","cóndor","buitre"],

  // History stories for reading comprehension
  stories: [
    {
      title: "La Independencia de México",
      level: "intermediate",
      text: `El 16 de septiembre de 1810, el cura Miguel Hidalgo pronunció el famoso Grito de Independencia en el pueblo de Dolores, Guanajuato. Este acto {1} el inicio de la guerra de independencia que {2} durante once años. El movimiento insurgente {3} a miles de campesinos e indígenas que {4} contra el dominio colonial español. Finalmente, el 27 de septiembre de 1821, el Ejército Trigarante, liderado por Agustín de Iturbide, {5} triunfante a la Ciudad de México, {6} así la independencia nacional. Este proceso histórico {7} profundamente la identidad del pueblo mexicano y {8} las bases de una nueva nación soberana.`,
      blanks: [
        {pos:1, options:["marcó","señaló","inició","comenzó"], correct:0, hint:"to mark/indicate"},
        {pos:2, options:["duraba","duró","duraría","durara"], correct:1, hint:"preterite of durar"},
        {pos:3, options:["atrajo","atraía","atrae","atraiga"], correct:0, hint:"attracted (preterite)"},
        {pos:4, options:["luchaban","lucharon","lucharán","luchen"], correct:0, hint:"were fighting (imperfect)"},
        {pos:5, options:["entró","entra","entrara","entrará"], correct:0, hint:"entered (preterite)"},
        {pos:6, options:["consolidando","consolidar","consolidó","consolidase"], correct:0, hint:"consolidating (gerund)"},
        {pos:7, options:["transformó","transforma","transforme","transformara"], correct:0, hint:"transformed (preterite)"},
        {pos:8, options:["estableció","establece","estableciera","establecerá"], correct:0, hint:"established (preterite)"},
      ],
      vocab: [
        {word:"cura",def:"priest"},
        {word:"pronunció",def:"pronounced/delivered"},
        {word:"insurgente",def:"insurgent/rebel"},
        {word:"campesino",def:"peasant/farmer"},
        {word:"dominio",def:"domination/rule"},
        {word:"soberana",def:"sovereign"},
      ]
    },
    {
      title: "Los Aztecas y Tenochtitlán",
      level: "intermediate",
      text: `Los aztecas, también conocidos como mexicas, {1} en el Valle de México alrededor del siglo XIV. Según la leyenda, sus dioses les {2} que {3} su ciudad donde {4} un águila {5} una serpiente sobre un nopal. En 1325, {6} Tenochtitlán sobre un islote en el lago Texcoco. La ciudad {7} rápidamente y {8} convertirse en una de las más grandes del mundo, con una población estimada de 200,000 habitantes. Los aztecas {9} un poderoso imperio que {10} a los pueblos vecinos mediante la guerra y la diplomacia.`,
      blanks: [
        {pos:1, options:["se establecieron","establecían","establezcan","se establecen"], correct:0, hint:"settled (reflexive preterite)"},
        {pos:2, options:["ordenaron","ordenaban","ordenarán","ordenen"], correct:0, hint:"ordered (preterite)"},
        {pos:3, options:["fundaran","fundarán","fundaron","fundan"], correct:0, hint:"they should found (subj.)"},
        {pos:4, options:["vieran","vieron","verían","ven"], correct:0, hint:"they would see (subj.)"},
        {pos:5, options:["devorando","devoró","devore","devorar"], correct:0, hint:"devouring (gerund)"},
        {pos:6, options:["fundaron","fundan","fundaban","fundarán"], correct:0, hint:"founded (preterite)"},
        {pos:7, options:["creció","crece","crecía","crezca"], correct:0, hint:"grew (preterite)"},
        {pos:8, options:["llegó a","llega a","llegará a","llegara a"], correct:0, hint:"came to (preterite + a)"},
        {pos:9, options:["construyeron","construyen","construían","construirán"], correct:0, hint:"built/constructed (preterite)"},
        {pos:10, options:["controló","controla","controlaba","controlará"], correct:0, hint:"controlled (preterite)"},
      ],
      vocab: [
        {word:"islote",def:"small island"},
        {word:"nopal",def:"cactus"},
        {word:"devorando",def:"devouring"},
        {word:"estimada",def:"estimated"},
        {word:"diplomacia",def:"diplomacy"},
        {word:"poderoso",def:"powerful"},
      ]
    },
    {
      title: "Simón Bolívar: El Libertador",
      level: "advanced",
      text: `Simón Bolívar, nacido en Caracas en 1783, {1} el sueño de unificar América del Sur en una gran nación libre del dominio español. Después de múltiples fracasos y exilios, {2} victorias cruciales en batallas como Boyacá (1819) y Carabobo (1821). Su visión {3} la creación de la Gran Colombia, una república que {4} Venezuela, Colombia, Ecuador y Panamá. Sin embargo, las tensiones políticas y los intereses regionales {5} su proyecto. Las naciones {6} separarse y Bolívar, {7} y enfermo, {8} en 1830 sin ver realizado su sueño continental. Su legado, sin embargo, {9} vivo en la memoria colectiva latinoamericana y lo {10} como el Padre de la Patria en varios países.`,
      blanks: [
        {pos:1, options:["persiguió","persigue","perseguía","perseguirá"], correct:2, hint:"was pursuing (imperfect - ongoing dream)"},
        {pos:2, options:["alcanzó","alcanza","alcanzara","alcanzaría"], correct:0, hint:"achieved (preterite)"},
        {pos:3, options:["contemplaba","contempló","contemple","contemplará"], correct:0, hint:"contemplated/envisioned (imperfect)"},
        {pos:4, options:["integrara","integró","integra","integrará"], correct:0, hint:"would integrate (subj.)"},
        {pos:5, options:["frustraron","frustran","frustrarán","frustren"], correct:0, hint:"frustrated (preterite)"},
        {pos:6, options:["prefirieron","prefieren","preferirían","prefieran"], correct:0, hint:"preferred (preterite)"},
        {pos:7, options:["desilusionado","desilusionar","desilusiona","desilusionando"], correct:0, hint:"disillusioned (past participle adj.)"},
        {pos:8, options:["falleció","fallece","fallecería","falleciera"], correct:0, hint:"passed away (preterite)"},
        {pos:9, options:["pervive","pervivió","pervivía","perviva"], correct:0, hint:"lives on (present - still true)"},
        {pos:10, options:["honran","honraron","honrarán","honren"], correct:0, hint:"honor (present - still true)"},
      ],
      vocab: [
        {word:"fracasos",def:"failures"},
        {word:"exilios",def:"exiles"},
        {word:"desilusionado",def:"disillusioned"},
        {word:"legado",def:"legacy"},
        {word:"colectiva",def:"collective"},
        {word:"contemplaba",def:"envisioned/contemplated"},
      ]
    },
  ],

  // Conjugation challenge data
  conjugations: [
    {verb:"hablar", tense:"presente", forms:{yo:"hablo",tú:"hablas",él:"habla","nosotros":"hablamos","ellos":"hablan"}, type:"regular"},
    {verb:"comer", tense:"presente", forms:{yo:"como",tú:"comes",él:"come","nosotros":"comemos","ellos":"comen"}, type:"regular"},
    {verb:"vivir", tense:"presente", forms:{yo:"vivo",tú:"vives",él:"vive","nosotros":"vivimos","ellos":"viven"}, type:"regular"},
    {verb:"ser", tense:"presente", forms:{yo:"soy",tú:"eres",él:"es","nosotros":"somos","ellos":"son"}, type:"irregular"},
    {verb:"estar", tense:"presente", forms:{yo:"estoy",tú:"estás",él:"está","nosotros":"estamos","ellos":"están"}, type:"irregular"},
    {verb:"tener", tense:"presente", forms:{yo:"tengo",tú:"tienes",él:"tiene","nosotros":"tenemos","ellos":"tienen"}, type:"irregular"},
    {verb:"ir", tense:"presente", forms:{yo:"voy",tú:"vas",él:"va","nosotros":"vamos","ellos":"van"}, type:"irregular"},
    {verb:"poder", tense:"presente", forms:{yo:"puedo",tú:"puedes",él:"puede","nosotros":"podemos","ellos":"pueden"}, type:"stem-change"},
    {verb:"querer", tense:"presente", forms:{yo:"quiero",tú:"quieres",él:"quiere","nosotros":"queremos","ellos":"quieren"}, type:"stem-change"},
    {verb:"saber", tense:"presente", forms:{yo:"sé",tú:"sabes",él:"sabe","nosotros":"sabemos","ellos":"saben"}, type:"irregular"},
    {verb:"hablar", tense:"pretérito", forms:{yo:"hablé",tú:"hablaste",él:"habló","nosotros":"hablamos","ellos":"hablaron"}, type:"regular"},
    {verb:"comer", tense:"pretérito", forms:{yo:"comí",tú:"comiste",él:"comió","nosotros":"comimos","ellos":"comieron"}, type:"regular"},
    {verb:"ir", tense:"pretérito", forms:{yo:"fui",tú:"fuiste",él:"fue","nosotros":"fuimos","ellos":"fueron"}, type:"irregular"},
    {verb:"ser", tense:"pretérito", forms:{yo:"fui",tú:"fuiste",él:"fue","nosotros":"fuimos","ellos":"fueron"}, type:"irregular"},
    {verb:"tener", tense:"pretérito", forms:{yo:"tuve",tú:"tuviste",él:"tuvo","nosotros":"tuvimos","ellos":"tuvieron"}, type:"irregular"},
    {verb:"hacer", tense:"pretérito", forms:{yo:"hice",tú:"hiciste",él:"hizo","nosotros":"hicimos","ellos":"hicieron"}, type:"irregular"},
    {verb:"poder", tense:"pretérito", forms:{yo:"pude",tú:"pudiste",él:"pudo","nosotros":"pudimos","ellos":"pudieron"}, type:"irregular"},
    {verb:"hablar", tense:"imperfecto", forms:{yo:"hablaba",tú:"hablabas",él:"hablaba","nosotros":"hablábamos","ellos":"hablaban"}, type:"regular"},
    {verb:"tener", tense:"futuro", forms:{yo:"tendré",tú:"tendrás",él:"tendrá","nosotros":"tendremos","ellos":"tendrán"}, type:"irregular"},
    {verb:"hablar", tense:"futuro", forms:{yo:"hablaré",tú:"hablarás",él:"hablará","nosotros":"hablaremos","ellos":"hablarán"}, type:"regular"},
  ],

  // Word pairs for translation game (EN -> ES)
  wordPairs: [
    // Basic
    {en:"freedom",es:"libertad"},{en:"homeland",es:"patria"},{en:"people",es:"pueblo"},
    {en:"king",es:"rey"},{en:"queen",es:"reina"},{en:"war",es:"guerra"},
    {en:"peace",es:"paz"},{en:"land",es:"tierra"},{en:"river",es:"río"},
    {en:"mountain",es:"montaña"},{en:"city",es:"ciudad"},{en:"village",es:"aldea"},
    {en:"soldier",es:"soldado"},{en:"leader",es:"líder"},{en:"enemy",es:"enemigo"},
    // History
    {en:"independence",es:"independencia"},{en:"revolution",es:"revolución"},
    {en:"constitution",es:"constitución"},{en:"congress",es:"congreso"},
    {en:"treaty",es:"tratado"},{en:"colony",es:"colonia"},
    {en:"empire",es:"imperio"},{en:"republic",es:"república"},
    {en:"democracy",es:"democracia"},{en:"slavery",es:"esclavitud"},
    {en:"indigenous",es:"indígena"},{en:"colonizer",es:"colonizador"},
    {en:"rebellion",es:"rebelión"},{en:"resistance",es:"resistencia"},
    {en:"liberation",es:"liberación"},{en:"conquest",es:"conquista"},
    // Advanced
    {en:"sovereignty",es:"soberanía"},{en:"nationalism",es:"nacionalismo"},
    {en:"oppression",es:"opresión"},{en:"reform",es:"reforma"},
    {en:"alliance",es:"alianza"},{en:"betrayal",es:"traición"},
    {en:"exile",es:"exilio"},{en:"legacy",es:"legado"},
    {en:"uprising",es:"levantamiento"},{en:"ceasefire",es:"alto al fuego"},
    {en:"declaration",es:"declaración"},{en:"ambassador",es:"embajador"},
    {en:"territory",es:"territorio"},{en:"border",es:"frontera"},
    {en:"wealth",es:"riqueza"},{en:"poverty",es:"pobreza"},
    // Nature/food
    {en:"corn/maize",es:"maíz"},{en:"cacao",es:"cacao"},
    {en:"avocado",es:"aguacate"},{en:"chili pepper",es:"chile"},
    {en:"jungle",es:"selva"},{en:"volcano",es:"volcán"},
    {en:"earthquake",es:"terremoto"},{en:"harvest",es:"cosecha"},
    {en:"drought",es:"sequía"},{en:"flood",es:"inundación"},
  ],

  // Hangman word bank with hints
  hangmanWords: [
    {word:"independencia",hint:"freedom from colonial rule"},
    {word:"revolución",hint:"major political upheaval"},
    {word:"libertador",hint:"title given to Simón Bolívar"},
    {word:"conquistador",hint:"Spanish explorer-soldier"},
    {word:"constitución",hint:"fundamental law document"},
    {word:"civilización",hint:"advanced human society"},
    {word:"esclavitud",hint:"the state of being enslaved"},
    {word:"emancipación",hint:"freedom from bondage"},
    {word:"mestizo",hint:"mixed Indigenous-European heritage"},
    {word:"caudillo",hint:"Latin American military leader"},
    {word:"hacienda",hint:"large rural estate"},
    {word:"malinche",hint:"Aztec interpreter for Cortés"},
    {word:"tlacuache",hint:"a marsupial native to Mexico"},
    {word:"quetzal",hint:"sacred bird of Guatemala"},
    {word:"aguacate",hint:"buttery green fruit"},
    {word:"chocolate",hint:"came from cacao, Aztec gift to the world"},
    {word:"huracán",hint:"powerful tropical storm"},
    {word:"volcán",hint:"mountain that erupts"},
    {word:"mariposa",hint:"butterfly"},
    {word:"murciélago",hint:"the only flying mammal"},
    {word:"chapulín",hint:"edible insect, also a TV character"},
    {word:"ferrocarril",hint:"trains run on this"},
    {word:"guerrillero",hint:"irregular warfare fighter"},
    {word:"pronunciamiento",hint:"military declaration of revolt"},
    {word:"tenochtitlán",hint:"Aztec capital, now Mexico City"},
    {word:"copacabana",hint:"Bolivian city on Lake Titicaca"},
    {word:"patagonia",hint:"southern tip of South America"},
    {word:"amazonia",hint:"vast South American rainforest"},
  ],

  // High-frequency vocabulary for everyday themed conversations.
  themedVocabulary: {
    gym: [
      {en:"gym",es:"gimnasio",type:"noun"},{en:"workout",es:"entrenamiento",type:"noun"},
      {en:"weight",es:"peso",type:"noun"},{en:"dumbbell",es:"mancuerna",type:"noun"},
      {en:"barbell",es:"barra",type:"noun"},{en:"machine",es:"máquina",type:"noun"},
      {en:"repetition",es:"repetición",type:"noun"},{en:"set",es:"serie",type:"noun"},
      {en:"muscle",es:"músculo",type:"noun"},{en:"strength",es:"fuerza",type:"noun"},
      {en:"to train",es:"entrenar",type:"verb"},{en:"to lift",es:"levantar",type:"verb"},
      {en:"to stretch",es:"estirar",type:"verb"},{en:"to breathe",es:"respirar",type:"verb"},
      {en:"to sweat",es:"sudar",type:"verb"},{en:"to rest",es:"descansar",type:"verb"},
      {en:"strong",es:"fuerte",type:"adjective"},{en:"tired",es:"cansado",type:"adjective"},
      {en:"heavy",es:"pesado",type:"adjective"},{en:"light",es:"ligero",type:"adjective"},
      {en:"sore",es:"adolorido",type:"adjective"},{en:"How many sets are left?",es:"¿Cuántas series te quedan?",type:"phrase"},
      {en:"Can I use this machine?",es:"¿Puedo usar esta máquina?",type:"phrase"},
      {en:"Do you need a spot?",es:"¿Necesitas que te ayude?",type:"phrase"},

      // Equipment and machines
      {en:"weight plate",es:"disco de pesas",type:"noun",subtopic:"equipment"},
      {en:"weight stack",es:"pila de pesas",type:"noun",subtopic:"equipment"},
      {en:"weight pin",es:"pasador de peso",type:"noun",subtopic:"equipment"},
      {en:"adjustable bench",es:"banco ajustable",type:"noun",subtopic:"equipment"},
      {en:"flat bench",es:"banco plano",type:"noun",subtopic:"equipment"},
      {en:"incline bench",es:"banco inclinado",type:"noun",subtopic:"equipment"},
      {en:"squat rack",es:"soporte para sentadillas",type:"noun",subtopic:"equipment"},
      {en:"power rack",es:"jaula de potencia",type:"noun",subtopic:"equipment"},
      {en:"Smith machine",es:"máquina Smith",type:"noun",subtopic:"equipment"},
      {en:"cable machine",es:"máquina de poleas",type:"noun",subtopic:"equipment"},
      {en:"high pulley",es:"polea alta",type:"noun",subtopic:"equipment"},
      {en:"low pulley",es:"polea baja",type:"noun",subtopic:"equipment"},
      {en:"cable attachment",es:"accesorio de polea",type:"noun",subtopic:"equipment"},
      {en:"straight bar attachment",es:"barra recta",type:"noun",subtopic:"equipment"},
      {en:"rope attachment",es:"agarre de cuerda",type:"noun",subtopic:"equipment"},
      {en:"V-grip handle",es:"agarre en V",type:"noun",subtopic:"equipment"},
      {en:"resistance band",es:"banda elástica",type:"noun",subtopic:"equipment"},
      {en:"lifting belt",es:"cinturón de levantamiento",type:"noun",subtopic:"equipment"},
      {en:"wrist straps",es:"correas de levantamiento",type:"noun",subtopic:"equipment"},
      {en:"wrist wraps",es:"muñequeras",type:"noun",subtopic:"equipment"},
      {en:"foam roller",es:"rodillo de espuma",type:"noun",subtopic:"equipment"},
      {en:"exercise mat",es:"colchoneta",type:"noun",subtopic:"equipment"},
      {en:"medicine ball",es:"balón medicinal",type:"noun",subtopic:"equipment"},
      {en:"kettlebell",es:"pesa rusa",type:"noun",subtopic:"equipment"},
      {en:"pull-up bar",es:"barra de dominadas",type:"noun",subtopic:"equipment"},
      {en:"dip station",es:"estación de fondos",type:"noun",subtopic:"equipment"},
      {en:"leg press",es:"prensa de piernas",type:"noun",subtopic:"equipment"},
      {en:"leg extension machine",es:"máquina de extensión de piernas",type:"noun",subtopic:"equipment"},
      {en:"leg curl machine",es:"máquina de curl femoral",type:"noun",subtopic:"equipment"},
      {en:"hack squat machine",es:"máquina de sentadilla hack",type:"noun",subtopic:"equipment"},
      {en:"calf raise machine",es:"máquina de elevación de gemelos",type:"noun",subtopic:"equipment"},
      {en:"hip abductor machine",es:"máquina de abductores",type:"noun",subtopic:"equipment"},
      {en:"hip adductor machine",es:"máquina de aductores",type:"noun",subtopic:"equipment"},
      {en:"chest press machine",es:"máquina de press de pecho",type:"noun",subtopic:"equipment"},
      {en:"pec deck machine",es:"máquina de aperturas de pecho",type:"noun",subtopic:"equipment"},
      {en:"lat pulldown machine",es:"máquina de jalón al pecho",type:"noun",subtopic:"equipment"},
      {en:"seated row machine",es:"máquina de remo sentado",type:"noun",subtopic:"equipment"},
      {en:"shoulder press machine",es:"máquina de press de hombros",type:"noun",subtopic:"equipment"},
      {en:"assisted pull-up machine",es:"máquina de dominadas asistidas",type:"noun",subtopic:"equipment"},
      {en:"treadmill",es:"cinta de correr",type:"noun",subtopic:"equipment"},
      {en:"stationary bike",es:"bicicleta estática",type:"noun",subtopic:"equipment"},
      {en:"elliptical trainer",es:"máquina elíptica",type:"noun",subtopic:"equipment"},
      {en:"rowing machine",es:"máquina de remo",type:"noun",subtopic:"equipment"},
      {en:"stair climber",es:"máquina de escaleras",type:"noun",subtopic:"equipment"},

      // Gym areas and services
      {en:"entrance",es:"entrada",type:"noun",subtopic:"facilities"},
      {en:"reception desk",es:"recepción",type:"noun",subtopic:"facilities"},
      {en:"membership card",es:"tarjeta de socio",type:"noun",subtopic:"facilities"},
      {en:"turnstile",es:"torno de acceso",type:"noun",subtopic:"facilities"},
      {en:"changing room",es:"vestuario",type:"noun",subtopic:"facilities"},
      {en:"locker",es:"taquilla",type:"noun",subtopic:"facilities"},
      {en:"locker-room bench",es:"banco del vestuario",type:"noun",subtopic:"facilities"},
      {en:"shower",es:"ducha",type:"noun",subtopic:"facilities"},
      {en:"hair dryer",es:"secador de pelo",type:"noun",subtopic:"facilities"},
      {en:"water station",es:"fuente de agua",type:"noun",subtopic:"facilities"},
      {en:"water-bottle filling station",es:"punto de llenado de botellas",type:"noun",subtopic:"facilities"},
      {en:"massage chair",es:"sillón de masaje",type:"noun",subtopic:"facilities"},
      {en:"stretching area",es:"zona de estiramientos",type:"noun",subtopic:"facilities"},
      {en:"free-weights area",es:"zona de peso libre",type:"noun",subtopic:"facilities"},
      {en:"machine area",es:"zona de máquinas",type:"noun",subtopic:"facilities"},
      {en:"cardio area",es:"zona de cardio",type:"noun",subtopic:"facilities"},
      {en:"functional-training area",es:"zona de entrenamiento funcional",type:"noun",subtopic:"facilities"},
      {en:"group-class studio",es:"sala de clases colectivas",type:"noun",subtopic:"facilities"},
      {en:"spinning room",es:"sala de ciclismo indoor",type:"noun",subtopic:"facilities"},
      {en:"stairs",es:"escaleras",type:"noun",subtopic:"facilities"},
      {en:"emergency exit",es:"salida de emergencia",type:"noun",subtopic:"facilities"},
      {en:"personal trainer",es:"entrenador personal",type:"noun",subtopic:"facilities"},
      {en:"gym member",es:"socio del gimnasio",type:"noun",subtopic:"facilities"},
      {en:"training partner",es:"compañero de entrenamiento",type:"noun",subtopic:"facilities"},

      // Anatomy, discomfort, and recovery
      {en:"chest muscles",es:"pectorales",type:"noun",subtopic:"anatomy"},
      {en:"upper back",es:"espalda alta",type:"noun",subtopic:"anatomy"},
      {en:"lower back",es:"zona lumbar",type:"noun",subtopic:"anatomy"},
      {en:"latissimus dorsi",es:"dorsal ancho",type:"noun",subtopic:"anatomy"},
      {en:"trapezius",es:"trapecio",type:"noun",subtopic:"anatomy"},
      {en:"rhomboids",es:"romboides",type:"noun",subtopic:"anatomy"},
      {en:"shoulders",es:"hombros",type:"noun",subtopic:"anatomy"},
      {en:"deltoids",es:"deltoides",type:"noun",subtopic:"anatomy"},
      {en:"rotator cuff",es:"manguito rotador",type:"noun",subtopic:"anatomy"},
      {en:"biceps",es:"bíceps",type:"noun",subtopic:"anatomy"},
      {en:"triceps",es:"tríceps",type:"noun",subtopic:"anatomy"},
      {en:"forearms",es:"antebrazos",type:"noun",subtopic:"anatomy"},
      {en:"abdominal muscles",es:"abdominales",type:"noun",subtopic:"anatomy"},
      {en:"core",es:"zona media",type:"noun",subtopic:"anatomy"},
      {en:"obliques",es:"oblicuos",type:"noun",subtopic:"anatomy"},
      {en:"glutes",es:"glúteos",type:"noun",subtopic:"anatomy"},
      {en:"hip flexors",es:"flexores de la cadera",type:"noun",subtopic:"anatomy"},
      {en:"quadriceps",es:"cuádriceps",type:"noun",subtopic:"anatomy"},
      {en:"hamstrings",es:"isquiotibiales",type:"noun",subtopic:"anatomy"},
      {en:"inner thighs",es:"aductores",type:"noun",subtopic:"anatomy"},
      {en:"outer thighs",es:"abductores",type:"noun",subtopic:"anatomy"},
      {en:"calves",es:"gemelos",type:"noun",subtopic:"anatomy"},
      {en:"Achilles tendon",es:"tendón de Aquiles",type:"noun",subtopic:"anatomy"},
      {en:"joint",es:"articulación",type:"noun",subtopic:"anatomy"},
      {en:"muscle soreness",es:"agujetas",type:"noun",subtopic:"anatomy"},
      {en:"muscle tightness",es:"tensión muscular",type:"noun",subtopic:"anatomy"},
      {en:"muscle cramp",es:"calambre muscular",type:"noun",subtopic:"anatomy"},
      {en:"muscle strain",es:"distensión muscular",type:"noun",subtopic:"anatomy"},
      {en:"inflammation",es:"inflamación",type:"noun",subtopic:"anatomy"},
      {en:"stiffness",es:"rigidez",type:"noun",subtopic:"anatomy"},
      {en:"sharp pain",es:"dolor agudo",type:"noun",subtopic:"anatomy"},
      {en:"dull ache",es:"dolor sordo",type:"noun",subtopic:"anatomy"},
      {en:"tingling",es:"hormigueo",type:"noun",subtopic:"anatomy"},
      {en:"numbness",es:"entumecimiento",type:"noun",subtopic:"anatomy"},

      // Exercises, programming, and advanced training concepts
      {en:"bench press",es:"press de banca",type:"noun",subtopic:"training"},
      {en:"incline press",es:"press inclinado",type:"noun",subtopic:"training"},
      {en:"overhead press",es:"press militar",type:"noun",subtopic:"training"},
      {en:"chest fly",es:"aperturas de pecho",type:"noun",subtopic:"training"},
      {en:"lat pulldown",es:"jalón al pecho",type:"noun",subtopic:"training"},
      {en:"seated cable row",es:"remo sentado en polea",type:"noun",subtopic:"training"},
      {en:"bent-over row",es:"remo inclinado",type:"noun",subtopic:"training"},
      {en:"face pull",es:"tirón a la cara",type:"noun",subtopic:"training"},
      {en:"pull-up",es:"dominada",type:"noun",subtopic:"training"},
      {en:"dip",es:"fondo",type:"noun",subtopic:"training"},
      {en:"push-up",es:"flexión",type:"noun",subtopic:"training"},
      {en:"squat",es:"sentadilla",type:"noun",subtopic:"training"},
      {en:"deadlift",es:"peso muerto",type:"noun",subtopic:"training"},
      {en:"Romanian deadlift",es:"peso muerto rumano",type:"noun",subtopic:"training"},
      {en:"hip thrust",es:"empuje de cadera",type:"noun",subtopic:"training"},
      {en:"lunge",es:"zancada",type:"noun",subtopic:"training"},
      {en:"Bulgarian split squat",es:"sentadilla búlgara",type:"noun",subtopic:"training"},
      {en:"calf raise",es:"elevación de gemelos",type:"noun",subtopic:"training"},
      {en:"lateral raise",es:"elevación lateral",type:"noun",subtopic:"training"},
      {en:"biceps curl",es:"curl de bíceps",type:"noun",subtopic:"training"},
      {en:"hammer curl",es:"curl martillo",type:"noun",subtopic:"training"},
      {en:"triceps pushdown",es:"extensión de tríceps en polea",type:"noun",subtopic:"training"},
      {en:"warm-up set",es:"serie de calentamiento",type:"noun",subtopic:"training"},
      {en:"working set",es:"serie efectiva",type:"noun",subtopic:"training"},
      {en:"drop set",es:"serie descendente",type:"noun",subtopic:"training"},
      {en:"superset",es:"superserie",type:"noun",subtopic:"training"},
      {en:"circuit training",es:"entrenamiento en circuito",type:"noun",subtopic:"training"},
      {en:"compound exercise",es:"ejercicio multiarticular",type:"noun",subtopic:"training"},
      {en:"isolation exercise",es:"ejercicio de aislamiento",type:"noun",subtopic:"training"},
      {en:"range of motion",es:"rango de movimiento",type:"noun",subtopic:"training"},
      {en:"training volume",es:"volumen de entrenamiento",type:"noun",subtopic:"training"},
      {en:"training frequency",es:"frecuencia de entrenamiento",type:"noun",subtopic:"training"},
      {en:"training intensity",es:"intensidad de entrenamiento",type:"noun",subtopic:"training"},
      {en:"progressive overload",es:"sobrecarga progresiva",type:"noun",subtopic:"training"},
      {en:"muscle hypertrophy",es:"hipertrofia muscular",type:"noun",subtopic:"training"},
      {en:"muscular endurance",es:"resistencia muscular",type:"noun",subtopic:"training"},
      {en:"mind-muscle connection",es:"conexión mente-músculo",type:"noun",subtopic:"training"},
      {en:"repetition in reserve",es:"repetición en reserva",type:"noun",subtopic:"training"},
      {en:"to failure",es:"al fallo",type:"phrase",subtopic:"training"},
      {en:"rest interval",es:"intervalo de descanso",type:"noun",subtopic:"training"},
      {en:"personal record",es:"marca personal",type:"noun",subtopic:"training"},
      {en:"training split",es:"división de la rutina",type:"noun",subtopic:"training"},
      {en:"upper body",es:"tren superior",type:"noun",subtopic:"training"},
      {en:"lower body",es:"tren inferior",type:"noun",subtopic:"training"},
      {en:"push day",es:"día de empuje",type:"noun",subtopic:"training"},
      {en:"pull day",es:"día de tirón",type:"noun",subtopic:"training"},
      {en:"leg day",es:"día de piernas",type:"noun",subtopic:"training"},
      {en:"recovery day",es:"día de recuperación",type:"noun",subtopic:"training"},

      // Technique and body-position cues
      {en:"Keep your back straight",es:"Mantén la espalda recta",type:"phrase",subtopic:"technique"},
      {en:"Keep a neutral spine",es:"Mantén la columna neutra",type:"phrase",subtopic:"technique"},
      {en:"Brace your core",es:"Activa la zona media",type:"phrase",subtopic:"technique"},
      {en:"Tighten your abdominal muscles",es:"Contrae los abdominales",type:"phrase",subtopic:"technique"},
      {en:"Pull your shoulder blades back",es:"Lleva los omóplatos hacia atrás",type:"phrase",subtopic:"technique"},
      {en:"Lower your shoulders",es:"Baja los hombros",type:"phrase",subtopic:"technique"},
      {en:"Keep your chest up",es:"Mantén el pecho erguido",type:"phrase",subtopic:"technique"},
      {en:"Keep your head aligned",es:"Mantén la cabeza alineada",type:"phrase",subtopic:"technique"},
      {en:"Look straight ahead",es:"Mira al frente",type:"phrase",subtopic:"technique"},
      {en:"Bend your knees slightly",es:"Flexiona ligeramente las rodillas",type:"phrase",subtopic:"technique"},
      {en:"Do not lock your knees",es:"No bloquees las rodillas",type:"phrase",subtopic:"technique"},
      {en:"Keep your knees in line with your toes",es:"Alinea las rodillas con los pies",type:"phrase",subtopic:"technique"},
      {en:"Place your feet shoulder-width apart",es:"Separa los pies al ancho de los hombros",type:"phrase",subtopic:"technique"},
      {en:"Plant your feet firmly",es:"Apoya bien los pies",type:"phrase",subtopic:"technique"},
      {en:"Drive through your heels",es:"Empuja desde los talones",type:"phrase",subtopic:"technique"},
      {en:"Push your hips back",es:"Lleva la cadera hacia atrás",type:"phrase",subtopic:"technique"},
      {en:"Squeeze your glutes",es:"Contrae los glúteos",type:"phrase",subtopic:"technique"},
      {en:"Keep your elbows close to your body",es:"Mantén los codos pegados al cuerpo",type:"phrase",subtopic:"technique"},
      {en:"Do not arch your lower back",es:"No arquees la zona lumbar",type:"phrase",subtopic:"technique"},
      {en:"Control the lowering phase",es:"Controla la fase de bajada",type:"phrase",subtopic:"technique"},
      {en:"Move slowly and with control",es:"Muévete despacio y con control",type:"phrase",subtopic:"technique"},
      {en:"Use the full range of motion",es:"Usa todo el rango de movimiento",type:"phrase",subtopic:"technique"},
      {en:"Do not use momentum",es:"No uses el impulso",type:"phrase",subtopic:"technique"},
      {en:"Exhale during the effort",es:"Suelta el aire durante el esfuerzo",type:"phrase",subtopic:"technique"},
      {en:"Inhale as you lower the weight",es:"Inspira al bajar el peso",type:"phrase",subtopic:"technique"},

      // Real interactions with members, trainers, and reception staff
      {en:"Are you using this bench?",es:"¿Estás usando este banco?",type:"phrase",subtopic:"conversation"},
      {en:"Is this machine free?",es:"¿Está libre esta máquina?",type:"phrase",subtopic:"conversation"},
      {en:"Can we take turns?",es:"¿Podemos turnarnos?",type:"phrase",subtopic:"conversation"},
      {en:"Can I work in with you?",es:"¿Podemos alternar las series?",type:"phrase",subtopic:"conversation"},
      {en:"How many sets do you have left?",es:"¿Cuántas series te faltan?",type:"phrase",subtopic:"conversation"},
      {en:"I have two sets left",es:"Me faltan dos series",type:"phrase",subtopic:"conversation"},
      {en:"Let me know when you finish",es:"Avísame cuando termines",type:"phrase",subtopic:"conversation"},
      {en:"Could you spot me?",es:"¿Me puedes ayudar con esta serie?",type:"phrase",subtopic:"conversation"},
      {en:"Only help me if the bar stops",es:"Ayúdame solo si se para la barra",type:"phrase",subtopic:"conversation"},
      {en:"Do not touch the bar yet",es:"No toques la barra todavía",type:"phrase",subtopic:"conversation"},
      {en:"Could you pass me that dumbbell?",es:"¿Me pasas esa mancuerna?",type:"phrase",subtopic:"conversation"},
      {en:"Could you move your bottle?",es:"¿Puedes mover tu botella?",type:"phrase",subtopic:"conversation"},
      {en:"Could you make some room?",es:"¿Puedes dejarme un poco de espacio?",type:"phrase",subtopic:"conversation"},
      {en:"Please put the weights back",es:"Por favor, guarda las pesas en su sitio",type:"phrase",subtopic:"conversation"},
      {en:"Please wipe down the machine",es:"Por favor, limpia la máquina después de usarla",type:"phrase",subtopic:"conversation"},
      {en:"What weight are you using?",es:"¿Con cuánto peso estás entrenando?",type:"phrase",subtopic:"conversation"},
      {en:"Can you lower the weight?",es:"¿Puedes bajar el peso?",type:"phrase",subtopic:"conversation"},
      {en:"Can you raise the seat?",es:"¿Puedes subir el asiento?",type:"phrase",subtopic:"conversation"},
      {en:"How do I adjust the seat?",es:"¿Cómo se ajusta el asiento?",type:"phrase",subtopic:"conversation"},
      {en:"Where does the pin go?",es:"¿Dónde se coloca el pasador?",type:"phrase",subtopic:"conversation"},
      {en:"How does this machine work?",es:"¿Cómo funciona esta máquina?",type:"phrase",subtopic:"conversation"},
      {en:"Could you show me the correct technique?",es:"¿Me puedes enseñar la técnica correcta?",type:"phrase",subtopic:"conversation"},
      {en:"Am I doing this correctly?",es:"¿Estoy haciendo bien este ejercicio?",type:"phrase",subtopic:"conversation"},
      {en:"Could you check my posture?",es:"¿Puedes corregirme la postura?",type:"phrase",subtopic:"conversation"},
      {en:"Where should I feel this exercise?",es:"¿Dónde debería notar este ejercicio?",type:"phrase",subtopic:"conversation"},
      {en:"Which muscles does this work?",es:"¿Qué músculos trabaja este ejercicio?",type:"phrase",subtopic:"conversation"},
      {en:"How can I train my upper back?",es:"¿Cómo puedo entrenar la espalda alta?",type:"phrase",subtopic:"conversation"},
      {en:"I want to focus more on my glutes",es:"Quiero centrarme más en los glúteos",type:"phrase",subtopic:"conversation"},
      {en:"I want to strengthen my lower back",es:"Quiero fortalecer la zona lumbar",type:"phrase",subtopic:"conversation"},
      {en:"I want to improve my shoulder mobility",es:"Quiero mejorar la movilidad de los hombros",type:"phrase",subtopic:"conversation"},
      {en:"I want to build muscle",es:"Quiero ganar masa muscular",type:"phrase",subtopic:"conversation"},
      {en:"I want to improve my endurance",es:"Quiero mejorar mi resistencia",type:"phrase",subtopic:"conversation"},
      {en:"I am training for strength",es:"Estoy entrenando para ganar fuerza",type:"phrase",subtopic:"conversation"},
      {en:"I am in a cutting phase",es:"Estoy en fase de definición",type:"phrase",subtopic:"conversation"},
      {en:"I am in a bulking phase",es:"Estoy en fase de volumen",type:"phrase",subtopic:"conversation"},
      {en:"Today I am training legs",es:"Hoy me toca entrenar piernas",type:"phrase",subtopic:"conversation"},
      {en:"I trained chest yesterday",es:"Ayer entrené pecho",type:"phrase",subtopic:"conversation"},
      {en:"My legs are very sore",es:"Tengo muchas agujetas en las piernas",type:"phrase",subtopic:"conversation"},
      {en:"My shoulder feels tight",es:"Noto el hombro cargado",type:"phrase",subtopic:"conversation"},
      {en:"I feel a sharp pain in my knee",es:"Siento un dolor agudo en la rodilla",type:"phrase",subtopic:"conversation"},
      {en:"My lower back hurts when I bend over",es:"Me duele la zona lumbar al inclinarme",type:"phrase",subtopic:"conversation"},
      {en:"This feels like muscle soreness",es:"Esto parecen agujetas",type:"phrase",subtopic:"conversation"},
      {en:"This does not feel like normal soreness",es:"Esto no parece una molestia normal",type:"phrase",subtopic:"conversation"},
      {en:"I need to reduce the load",es:"Necesito reducir la carga",type:"phrase",subtopic:"conversation"},
      {en:"I am recovering from an injury",es:"Me estoy recuperando de una lesión",type:"phrase",subtopic:"conversation"},
      {en:"I am going to stop because it hurts",es:"Voy a parar porque me duele",type:"phrase",subtopic:"conversation"},
      {en:"Where are the changing rooms?",es:"¿Dónde están los vestuarios?",type:"phrase",subtopic:"conversation"},
      {en:"How do the lockers work?",es:"¿Cómo funcionan las taquillas?",type:"phrase",subtopic:"conversation"},
      {en:"Do I need my own padlock?",es:"¿Necesito traer mi propio candado?",type:"phrase",subtopic:"conversation"},
      {en:"Are the showers included?",es:"¿Las duchas están incluidas?",type:"phrase",subtopic:"conversation"},
      {en:"Where can I refill my bottle?",es:"¿Dónde puedo rellenar la botella?",type:"phrase",subtopic:"conversation"},
      {en:"Is the massage chair free?",es:"¿Está libre el sillón de masaje?",type:"phrase",subtopic:"conversation"},
      {en:"What time does the gym close?",es:"¿A qué hora cierra el gimnasio?",type:"phrase",subtopic:"conversation"},
      {en:"I forgot my membership card",es:"He olvidado mi tarjeta de socio",type:"phrase",subtopic:"conversation"},
      {en:"My locker will not open",es:"Mi taquilla no se abre",type:"phrase",subtopic:"conversation"},
      {en:"The treadmill is not working",es:"La cinta de correr no funciona",type:"phrase",subtopic:"conversation"},
      {en:"Is there a beginner class?",es:"¿Hay alguna clase para principiantes?",type:"phrase",subtopic:"conversation"},
      {en:"I would like to book a personal-training session",es:"Quisiera reservar una sesión de entrenamiento personal",type:"phrase",subtopic:"conversation"}
    ],
    boardGames: [
      {en:"board game",es:"juego de mesa",type:"noun"},{en:"board",es:"tablero",type:"noun"},
      {en:"card",es:"carta",type:"noun"},{en:"deck",es:"baraja",type:"noun"},
      {en:"die",es:"dado",type:"noun"},{en:"token",es:"ficha",type:"noun"},
      {en:"turn",es:"turno",type:"noun"},{en:"rule",es:"regla",type:"noun"},
      {en:"score",es:"puntuación",type:"noun"},{en:"team",es:"equipo",type:"noun"},
      {en:"to shuffle",es:"barajar",type:"verb"},{en:"to roll",es:"tirar",type:"verb"},
      {en:"to draw a card",es:"robar una carta",type:"verb"},{en:"to discard",es:"descartar",type:"verb"},
      {en:"to win",es:"ganar",type:"verb"},{en:"to lose",es:"perder",type:"verb"},
      {en:"cooperative",es:"cooperativo",type:"adjective"},{en:"competitive",es:"competitivo",type:"adjective"},
      {en:"strategic",es:"estratégico",type:"adjective"},{en:"random",es:"aleatorio",type:"adjective"},
      {en:"Whose turn is it?",es:"¿A quién le toca?",type:"phrase"},
      {en:"It is your turn",es:"Te toca",type:"phrase"},
      {en:"How do you play?",es:"¿Cómo se juega?",type:"phrase"},
      {en:"That move is not allowed",es:"Esa jugada no está permitida",type:"phrase"}
    ],
    love: [
      {en:"love",es:"amor",type:"noun"},{en:"couple",es:"pareja",type:"noun"},
      {en:"date",es:"cita",type:"noun"},{en:"relationship",es:"relación",type:"noun"},
      {en:"kiss",es:"beso",type:"noun"},{en:"hug",es:"abrazo",type:"noun"},
      {en:"trust",es:"confianza",type:"noun"},{en:"affection",es:"cariño",type:"noun"},
      {en:"to love",es:"amar",type:"verb"},{en:"to fall in love",es:"enamorarse",type:"verb"},
      {en:"to miss someone",es:"echar de menos",type:"verb"},{en:"to kiss",es:"besar",type:"verb"},
      {en:"to hug",es:"abrazar",type:"verb"},{en:"to trust",es:"confiar",type:"verb"},
      {en:"to break up",es:"romper",type:"verb"},{en:"to forgive",es:"perdonar",type:"verb"},
      {en:"loving",es:"cariñoso",type:"adjective"},{en:"faithful",es:"fiel",type:"adjective"},
      {en:"single",es:"soltero",type:"adjective"},{en:"in love",es:"enamorado",type:"adjective"},
      {en:"I like you",es:"Me gustas",type:"phrase"},{en:"I love you",es:"Te quiero",type:"phrase"},
      {en:"I miss you",es:"Te echo de menos",type:"phrase"},
      {en:"Would you like to go out with me?",es:"¿Quieres salir conmigo?",type:"phrase"}
    ]
  },

  knowledgeQuizzes: {
    popCulture: {
      title:"📺 Pop Culture Spotlight", color:"#7c6aeb",
      questions:[
        {q:"¿Qué presentador es conocido por «El Hormiguero»?",a:"Pablo Motos",o:["Pablo Motos","Jordi Évole","David Broncano","Andreu Buenafuente"],x:"El presentador = the TV host."},
        {q:"¿Qué concurso presenta preguntas y una prueba final llamada «El Rosco»?",a:"Pasapalabra",o:["Pasapalabra","MasterChef","Saber y ganar","La Revuelta"],x:"El rosco is the circular alphabet challenge."},
        {q:"¿Quién creó y protagonizó la serie «Paquita Salas» junto con Javier Calvo?",a:"Javier Ambrossi",o:["Javier Ambrossi","Antonio Banderas","Pedro Almodóvar","Santiago Segura"],x:"Javier Calvo and Javier Ambrossi are known as Los Javis."},
        {q:"¿Qué actriz española protagonizó «Volver» y ganó un Óscar por «Vicky Cristina Barcelona»?",a:"Penélope Cruz",o:["Penélope Cruz","Paz Vega","Carmen Maura","Maribel Verdú"],x:"Protagonizar = to star in."},
        {q:"¿Quién dirige películas como «Todo sobre mi madre» y «Volver»?",a:"Pedro Almodóvar",o:["Pedro Almodóvar","Álex de la Iglesia","J. A. Bayona","Alejandro Amenábar"],x:"Dirigir una película = to direct a film."},
        {q:"¿Qué cocinero presenta «Pesadilla en la cocina» en España?",a:"Alberto Chicote",o:["Alberto Chicote","Karlos Arguiñano","Dabiz Muñoz","Jordi Cruz"],x:"El cocinero = the cook or chef."},
        {q:"¿Qué serie española sobre un atraco se convirtió en un éxito mundial?",a:"La casa de papel",o:["La casa de papel","Cuéntame cómo pasó","Aquí no hay quien viva","Élite"],x:"Un atraco = a robbery or heist."},
        {q:"¿Qué humorista y presentador conduce «La Revuelta»?",a:"David Broncano",o:["David Broncano","Pablo Motos","Jesús Calleja","Carlos Sobera"],x:"Conducir can mean to host a programme."},
        {q:"¿Qué programa de cocina convierte a aficionados en concursantes?",a:"MasterChef España",o:["MasterChef España","El Intermedio","La Voz","First Dates"],x:"El concursante = the contestant."},
        {q:"¿Qué actor español interpretó al Zorro y al Gato con Botas?",a:"Antonio Banderas",o:["Antonio Banderas","Javier Bardem","Mario Casas","Luis Tosar"],x:"Interpretar un papel = to play a role."},
        {q:"¿Qué veterano concurso cultural presenta Jordi Hurtado?",a:"Saber y ganar",o:["Saber y ganar","Pasapalabra","Boom","Atrapa un millón"],x:"Veterano means long-running here."},
        {q:"¿Qué serie sigue la vida de la familia Alcántara durante la historia reciente de España?",a:"Cuéntame cómo pasó",o:["Cuéntame cómo pasó","Los Serrano","Física o química","Vis a vis"],x:"Seguir la vida = to follow the life."}
      ]
    },
    geography: {
      title:"🗺️ Spain Explorer", color:"#4a9e8a",
      questions:[
        {q:"¿Cuál es la capital de España?",a:"Madrid",o:["Madrid","Barcelona","Sevilla","Valencia"],x:"La capital está en el centro de la península."},
        {q:"¿En qué comunidad autónoma está Sevilla?",a:"Andalucía",o:["Andalucía","Extremadura","Murcia","Castilla-La Mancha"],x:"La comunidad autónoma = autonomous community."},
        {q:"¿Qué cordillera separa España de Francia?",a:"Los Pirineos",o:["Los Pirineos","La Sierra Nevada","Los Picos de Europa","El Sistema Central"],x:"La cordillera = mountain range."},
        {q:"¿Cuál es el río más largo de la península ibérica?",a:"El Tajo",o:["El Tajo","El Ebro","El Duero","El Guadalquivir"],x:"El Tajo atraviesa España y Portugal."},
        {q:"¿Qué archipiélago español está en el océano Atlántico, cerca de África?",a:"Las Islas Canarias",o:["Las Islas Canarias","Las Islas Baleares","Las Cíes","Las Columbretes"],x:"El archipiélago = archipelago."},
        {q:"¿Cuál es la capital de Galicia?",a:"Santiago de Compostela",o:["Santiago de Compostela","A Coruña","Vigo","Lugo"],x:"También es el destino del famoso Camino."},
        {q:"¿En qué ciudad está la Alhambra?",a:"Granada",o:["Granada","Córdoba","Toledo","Málaga"],x:"La Alhambra domina la ciudad desde una colina."},
        {q:"¿Qué mar baña la costa de Barcelona?",a:"El Mediterráneo",o:["El Mediterráneo","El Cantábrico","El Atlántico","El mar de Alborán"],x:"Bañar la costa = to border or wash the coast."},
        {q:"¿Cuál es la montaña más alta de España?",a:"El Teide",o:["El Teide","El Mulhacén","El Aneto","El Moncayo"],x:"El Teide está en Tenerife."},
        {q:"¿Qué comunidad autónoma tiene Bilbao como ciudad más poblada?",a:"El País Vasco",o:["El País Vasco","Navarra","Cantabria","La Rioja"],x:"Poblada = populated."},
        {q:"¿Cuál de estas ciudades está en Castilla y León?",a:"Salamanca",o:["Salamanca","Alicante","Girona","Huelva"],x:"Salamanca es famosa por su universidad."},
        {q:"¿Qué río atraviesa Zaragoza?",a:"El Ebro",o:["El Ebro","El Miño","El Segura","El Júcar"],x:"Atravesar = to cross or run through."}
      ]
    },
    politicsHistory: {
      title:"🏛️ Politics & History", color:"#e8a838",
      questions:[
        {q:"¿Cómo se llama la cámara baja de las Cortes Generales?",a:"El Congreso de los Diputados",o:["El Congreso de los Diputados","El Senado","El Consejo de Estado","El Tribunal Supremo"],x:"La cámara baja = the lower house."},
        {q:"¿Qué texto establece los derechos y la organización política actual de España?",a:"La Constitución de 1978",o:["La Constitución de 1978","El Código Civil","Los Pactos de la Moncloa","El Estatuto Real"],x:"Establecer = to establish."},
        {q:"España es actualmente una…",a:"monarquía parlamentaria",o:["monarquía parlamentaria","república presidencial","monarquía absoluta","federación presidencial"],x:"La jefatura del Estado y el gobierno son funciones distintas."},
        {q:"¿Qué período comenzó tras la muerte de Franco y condujo a la democracia?",a:"La Transición",o:["La Transición","La Reconquista","La Restauración","La Regencia"],x:"Conducir a = to lead to."},
        {q:"¿En qué año terminó la Guerra Civil española?",a:"1939",o:["1939","1931","1945","1975"],x:"Terminar = to end."},
        {q:"¿Qué dos monarcas son conocidos como los Reyes Católicos?",a:"Isabel de Castilla y Fernando de Aragón",o:["Isabel de Castilla y Fernando de Aragón","Juana y Felipe","Carlos I e Isabel de Portugal","Alfonso X y Violante"],x:"Los monarcas = the monarchs."},
        {q:"¿Qué ocurrió en 1492 además del viaje de Colón?",a:"La conquista de Granada",o:["La conquista de Granada","La batalla de Lepanto","La Guerra de Sucesión","La proclamación de la República"],x:"La conquista puso fin al reino nazarí de Granada."},
        {q:"¿Qué pueblo construyó el acueducto de Segovia?",a:"Los romanos",o:["Los romanos","Los visigodos","Los fenicios","Los íberos"],x:"Construir = to build."},
        {q:"¿Cómo se llama una propuesta de ley debatida por el parlamento?",a:"Un proyecto de ley",o:["Un proyecto de ley","Una sentencia","Un padrón","Un decreto municipal"],x:"Debatir una ley = to debate a law."},
        {q:"¿Qué institución interpreta la Constitución española?",a:"El Tribunal Constitucional",o:["El Tribunal Constitucional","El Banco de España","El Senado","El Defensor del Pueblo"],x:"Interpretar aquí means to determine its constitutional meaning."},
        {q:"¿Qué civilización fundó ciudades como Emerita Augusta, hoy Mérida?",a:"La romana",o:["La romana","La celta","La cartaginesa","La visigoda"],x:"Fundar = to found."},
        {q:"¿Cómo se llama el derecho de elegir representantes mediante el voto?",a:"El sufragio",o:["El sufragio","El indulto","El escaño","El mandato"],x:"El sufragio = suffrage or the right to vote."}
      ]
    }
  },

  // These are original educational mini-passages, not song lyrics.
  musicCloze: [
    {song:"Mediterráneo",artist:"Joan Manuel Serrat",text:"La voz poética {recuerda|remembers} el mar y se siente profundamente {unida|connected} a su paisaje.",note:"A landmark singer-songwriter portrait of the Mediterranean."},
    {song:"Hijo de la luna",artist:"Mecano",text:"Esta historia musical {convierte|turns} una antigua leyenda en un relato {trágico|tragic} y misterioso.",note:"One of Mecano’s best-known narrative songs."},
    {song:"Entre dos tierras",artist:"Héroes del Silencio",text:"El protagonista se siente {atrapado|trapped} entre decisiones y debe {enfrentarse|face} a sus contradicciones.",note:"A defining Spanish rock anthem."},
    {song:"La chica de ayer",artist:"Nacha Pop",text:"El narrador {evoca|evokes} un encuentro del pasado mientras la ciudad parece {despertarse|wake up}.",note:"An emblematic song of the Movida madrileña."},
    {song:"Libre",artist:"Nino Bravo",text:"La canción celebra a quien {persigue|pursues} la libertad aunque el camino resulte {peligroso|dangerous}.",note:"A celebrated dramatic pop ballad."},
    {song:"Eres tú",artist:"Mocedades",text:"La persona amada se {compara|is compared} con elementos naturales que resultan {esenciales|essential} para vivir.",note:"Spain’s 1973 Eurovision runner-up and an international hit."},
    {song:"Y viva España",artist:"Manolo Escobar",text:"Este pasodoble {celebra|celebrates} el país con un tono festivo y un estribillo {inolvidable|unforgettable}.",note:"A fixture at popular celebrations and sporting events."},
    {song:"Macarena",artist:"Los del Río",text:"Su baile {cruzó|crossed} fronteras y la canción se {convirtió|became} en un fenómeno mundial.",note:"One of Spain’s biggest global dance hits."},
    {song:"Aserejé",artist:"Las Ketchup",text:"Un ritmo {pegadizo|catchy} y una coreografía sencilla {impulsaron|drove} su éxito internacional.",note:"A worldwide number one from 2002."},
    {song:"Corazón partío",artist:"Alejandro Sanz",text:"La voz describe una ruptura y {pregunta|asks} quién podrá {curar|heal} el dolor emocional.",note:"A signature Spanish pop song of the 1990s."},
    {song:"A quién le importa",artist:"Alaska y Dinarama",text:"El mensaje {defiende|defends} la identidad propia y {rechaza|rejects} vivir según la opinión ajena.",note:"An enduring anthem of individuality."},
    {song:"Resistiré",artist:"Dúo Dinámico",text:"La persona promete que {mantendrá|will maintain} su fuerza cuando la vida se vuelva {difícil|difficult}.",note:"A song strongly associated with collective resilience."},
    {song:"20 de abril",artist:"Celtas Cortos",text:"Una carta {recuerda|recalls} viejos amigos y se {pregunta|wonders} cuánto han cambiado sus vidas.",note:"A generational folk-rock song framed as a letter."},
    {song:"Devuélveme a mi chica",artist:"Hombres G",text:"El narrador expresa sus celos con humor y {reclama|demands back} una relación que ha {perdido|lost}.",note:"A playful classic of 1980s Spanish pop rock."},
    {song:"Por la boca vive el pez",artist:"Fito & Fitipaldis",text:"La letra reflexiona sobre cómo las palabras pueden {revelar|reveal} deseos y también {complicarnos|complicate for us} la vida.",note:"A major hit in contemporary Spanish rock."},
    {song:"Malamente",artist:"Rosalía",text:"La artista {mezcla|mixes} tradición flamenca y producción moderna para crear una atmósfera {inquietante|unsettling}.",note:"A landmark in the global rise of modern flamenco-pop."},
    {song:"Antes de morirme",artist:"C. Tangana y Rosalía",text:"Dos voces {confiesan|confess} deseos urgentes y reconocen que el tiempo puede {acabarse|run out}.",note:"An influential collaboration in Spain’s urban music scene."},
    {song:"Despechá",artist:"Rosalía",text:"Después de una decepción, la protagonista decide {divertirse|have fun} y sentirse {independiente|independent}.",note:"A globally successful summer pop track."},
    {song:"Quédate",artist:"Quevedo y Bizarrap",text:"El narrador {recuerda|remembers} una noche intensa y pide que la otra persona no se {marche|leave}.",note:"A global chart-topping session by a Spanish artist."},
    {song:"Mi gran noche",artist:"Raphael",text:"El cantante {imagina|imagines} una velada extraordinaria en la que podría {encontrar|find} el amor.",note:"A theatrical pop standard that remains widely celebrated."}
  ],

  // Curated excerpts supplied directly by the user.
  providedLyrics: [
    {
      song:"Mayores", artist:"Becky G feat. Bad Bunny", supplied:true,
      text:"Me gusta que me {traten|treat me} como dama\nMe gusta que me digan {poesía|poetry}\nMe gusta un {caballero|gentleman}\nQue sea {interesante|interesting}\nQue sea un buen {amigo|friend}\nPero más un buen {amante|lover}\n¿Qué importan unos años de {más|more}?\nDe los que te {abren|open} la puerta\nY te mandan {flores|flowers}\nLos besos que quiera {darme|give me}\nY que me vuelva {loca|crazy}\nYo te prometo un millón de {aventuras|adventures}\nYo no quiero un niño que no {sepa|knows} nada",
      note:"User-supplied lyrics; repeated and explicit sections condensed."
    },
    {
      song:"Criminal", artist:"Natti Natasha & Ozuna", supplied:true,
      text:"{Miento|I lie} si te digo que en ti no ando pensando\nQuisiera {saber|know} lo que estás haciendo\nTe llamo pero me sale {ocupado|busy}\nTú me {robaste|stole} el corazón\nNo puedo {negarlo|deny it}\nDe lejos yo puedo {observar|observe}\nTú me dices que yo me dejo {llevar|carried away}\nBáilame pero con {coraje|courage}\nTú eres un {delito|crime} que yo quiero cometer\nTú me {encantas|delight me}\nNo te quiero {compartir|share}\nMi cuerpo a ti te {extraña|misses}",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
    {
      song:"Chantaje", artist:"Shakira feat. Maluma", supplied:true,
      text:"Cuando está bien, te {alejas|move away} de mí\nTe sientes {sola|alone} y siempre estoy ahí\nEs una {guerra|war} de toma y dame\nNo me dejes con las {ganas|desire}\nVen y dímelo en la {cara|face}\nNunca tuve una mala {intención|intention}\nNunca quise {burlarme|make fun} de ti\nConmigo nunca se {sabe|knows}\nSiempre es a tu {manera|way}\nVas {libre|free} como el aire\nSabes {manipularme|manipulate me} bien\nNo pares bola a esa mala {propaganda|rumour}\nSigo tras de ti, {muriendo|dying} por ti",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
    {
      song:"Déjala Que Vuelva", artist:"Piso 21 feat. Manuel Turizo", supplied:true,
      text:"¿Cómo podrás {respirar|breathe} cuando te falte mi piel?\nSi fuiste tú quien se {alejó|moved away}\nNo quiero verte {llorar|cry} por mí\nEntiendo, no sabes {perder|lose}\nNo va a ser tan {fácil|easy}\nLa tengo {clara|clear}\nElla {conoce|knows} solita el camino conmigo\nNo dejo de {pensar|think} en tus besos\nYo sé que tú también {verás|will see}\nNo le {insistas|insist}\nSientes que por volver a ella {mueres|you die}",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
    {
      song:"Con Altura", artist:"ROSALÍA & J Balvin feat. El Guincho", supplied:true,
      text:"Esto vamos a {arrancarlo|start it} con altura\nEl dembow lo canto con {hondura|depth}\nDe Héctor aprendí la {sabrosura|flair}\nNunca viste una joya tan {pura|pure}\nLo que yo hago {dura|lasts}\nDemasiadas noches de {travesuras|mischief}\nVivo rápido y no tengo {cura|cure}\nIré joven para la {sepultura|grave}\nLo hago para mi gente y a mi {manera|way}\nPonte el {cinturón|seat belt} y coge asiento\nEl dinero nunca pierde {tiempo|time}\nCon el tiempo nos seguimos {elevando|rising}",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
    {
      song:"Mi Gente", artist:"J Balvin & Willy William", supplied:true,
      text:"Si el {ritmo|rhythm} te lleva a mover la cabeza\nMi música no {discrimina|discriminates} a nadie\nToda mi gente se {mueve|moves}\nHago música que {entretiene|entertains}\nLa fiesta no {para|stops}, apenas comienza\nEl mundo es grande, pero lo tengo en mis {manos|hands}\nCon el tiempo nos seguimos {elevando|rising}\nEsta fiesta no tiene {fin|end}",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
    {
      song:"Échame la Culpa", artist:"Luis Fonsi feat. Demi Lovato", supplied:true,
      text:"Tengo en esta historia algo que {confesar|confess}\nYa entendí muy bien qué fue lo que {pasó|happened}\nAunque duela, tengo que {aceptar|accept}\nNo me conociste nunca de {verdad|truly}\nYa se fue la {magia|magic} que te enamoró\nNo te quiero hacer {sufrir|suffer}\nEs mejor {olvidar|forget} y dejarlo así\nEse beso que siempre te {prometí|promised}",
      note:"User-supplied lyrics; repeated refrains and English sections condensed."
    },
    {
      song:"Bésame Mucho", artist:"Consuelo Velázquez", supplied:true,
      text:"Bésame, bésame mucho\nComo si fuera esta la noche la {última|last} vez\nQue tengo {miedo|fear} a perderte\nQuiero {tenerte|have you} muy cerca\nMirarme en tus ojos\nVerte {junto|next} a mí\nYo ya estaré {lejos|far away} de aquí",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
    {
      song:"Tití Me Preguntó", artist:"Bad Bunny", supplied:true,
      text:"Tití me {preguntó|asked me} si tengo muchas novias\nHoy tengo a una, mañana otra, pero no hay {boda|wedding}\nQue sonrían las que ya se {olvidaron|forgot} de mí\nTengo una colombiana que me {escribe|writes} todos los días\nYo dejo que jueguen con mi {corazón|heart}\nTe envío la {invitación|invitation}\nYo quisiera {enamorarme|fall in love}\nYo no {confío|trust}, ni en mí mismo confío",
      note:"User-supplied lyrics; repeated and explicit sections condensed."
    },
    {
      song:"LA FAMA", artist:"ROSALÍA feat. The Weeknd", supplied:true,
      text:"Lo que {pasó|happened}\nA ti te lo {cuento|I tell}\nNo creas que no {dolió|it hurt}\nPero me {obsesioné|I became obsessed}\nEs demasiado {traicionera|treacherous}\nSabe que será {celosa|jealous}\nMe ha dejado en {vela|awake}\nPuñaladas da su {ambición|ambition}",
      note:"User-supplied lyrics; repeated refrains condensed."
    },
  ],
};
